- device/globals/background_area.gd
The new background_area and item_background area scripts are great, but using them is more difficult than it needs to be. This is especially problematic since the new features are mostly undocumented, but having to first set the shape, then figure out how to set a transform and extents is also tricker than the old method of using a TextureFrame for background input, which only requires the user to attach a script.
What this addition does is to automatically set the shape on the Area2D which is used for background input, given that a node named "background" exists. For an example use case, see https://github.com/fleskesvor/escoria/tree/feat/simpler-background-area-test, which also uses the item_background script to make the mountain in the test scene respond to user input.
> Programmatically set RectangleShape2D on background area

- device/globals/game.gd
- device/globals/item_background.gd
Toggle boolean 'clicked' on item_background on mouse press/release to prevent simultaneous clicks on background_area. This should resolve #20.
See https://github.com/fleskesvor/escoria/tree/test/greedy_background_area for a test case using the mountain from device/scenes/test/test.scn as an item_background.
> Make background_area ignore item_background clicks

- device/globals/game.tscn
This does not fix all the problems in #46 but at least it places the camera on the player and respects camera limits, so that's something.
The camera is still zoomed wrong, but I'm almost sure this is a step in the right direction.
> [RFC] Set `current = true` on camera to follow player

- device/globals/global_vm.gd
- device/globals/main.gd
- device/globals/scene_base.gd
This replaces #56 as discussed on IRC/#escoria.
It introduces a `ready` event that can be used when attaching an esc script to a scene.
> Allow setting esc script on scene.gd node and run load commands

- device/globals/background.gd
- device/globals/background_area.gd
- device/globals/game.gd
- device/globals/item.gd
- device/project.godot
This makes for a more latter-day SCUMM experience.
> Have a setting so the right mouse button can open the action menu

- device/globals/game.gd
- device/globals/inventory.gd
- device/project.godot
This is not complete yet, but opened to gather preliminary feedback. There is even a non- yet near-zero possibility I'll be committing to it today.
The inventory is very broken as it stands in master, and something like the in-game buttons are not documented in the book (#45 flossmanualsfr#15).
I can only guess at what the intentions originally were here and try to fix accordingly. For what it's worth, with these changes in, I can hit the tab key to open an inventory and complaints are benign instead of crashing everything.
I have not created the in-game buttons and would hope that the branch goes in as is now, or with minimal changes, and someone else fix the buttons without me. This is because I do not currently see a need to have the buttons in anything I'm working on and it's a huge …
> Fixing the inventory

- device/globals/dialog_instance.gd
- device/project.godot
Because the actual variable is sort of convolutedly hidden, this makes configuration easier.
> Setting to force disabling typewriter speech

- device/globals/hud.gd
- device/project.godot
IMO this code should all be removed and replaced with something under `doc/` on how to create in-game buttons if someone wants it.
@StraToN @fleskesvor what do you think? Should this just be replaced with documentation? Would you write it?
> Show in-game buttons is broken, remove it so Escoria does not crash

- device/globals/game.gd
- device/globals/player.gd
- device/globals/terrain.gd
Because sometimes a scaled-down player sprite can take annoyingly long to cross the screen. By default the speed is not affected.
Also make double-clicking move the player faster, as is customary in modern adventure games. The default is a multiplier of 1.5.
> Variables to affect player speed

- device/globals/esc_compile.gd
- device/globals/global_vm.gd
- device/globals/vm_level.gd
- device/project.godot
This is the most likely cause for Heisenbugs and waste of time while developing something else. It was not even widely used.
Godot should take care of loading well enough without reinventing any wheels. Modern computers are fast. Kernels have file system caches. There are probably even more reasons why not to overcomplicate things.
Therefore, to simplify the code and to make caching-related bugs impossible, throw it out.
No perceptible difference in performance and the demo test scene works as expected.
The commits are split into smaller pieces if that makes discussion easier, and although I hope this history can be merged as-is, I can - of course - also squash them.
> Make cache system explicit

- device/globals/esc_compile.gd
- device/globals/game.gd
- device/globals/game_am.tscn
- device/globals/global_vm.gd
- device/globals/hud.gd
- device/globals/vm_level.gd
- device/project.godot
- device/ui/hud_minimal.tscn
- doc/hud.md
This builds on #79 
It fixes a bug where the action menu was opened in the wrong coordinates.
It also contains work to not have a verb menu in a game that uses an action menu.
It does not break the demo test scene.
It introduces settings for which hud to use and also the ability to change the inventory.
I'm more than happy that this allowed me to get rid of all my editing of `hud.tscn`, a major win in separating the framework from the game being developed :)
The problem was that the verb menu was really hard to get rid of. Even now there is a placholder in `game.tscn`, which is annoying, but must remain for now. The branch is getting out of control and the annoyance is so small, that for the time being, it would be most efficient to merge this branch.
Notes for the future: if Escoria …
> Camera zoom with HUD extensions

- device/globals/esc_compile.gd
- device/globals/global_vm.gd
- device/globals/vm_level.gd
This PR introduces an ESC command to set the zoom in height pixels.
It also fixes the bug when the player is standing on a sizemap and a zoom happens, now the sprite is scaled as well.
I threw in a fix for the `set_camera_pos` command for good measure, it must have been broken by the big regexp change way back.
@fleskesvor wanna confirm this is fine?
> Zoom height

- device/globals/background_area.gd
- device/globals/game.gd
- doc/background.md
This updates the automatic generation of a shape for the background when using a Sprite node to work with Godot 3, and also uses a Sprite instead of an Area2D to make it more similar to using a TextureRect node for the background. To make the process more straight-forward, the Area2D node is also generated from code, so these are the only steps required to use a background_area
1. create background Sprite and attach image
2. disable centering of Sprite node
3. attach background_area.gd script
Step 2 should probably be done automatically, but it will not be visible to the developer unless the script is made into a tool script, so maybe it's best to just document this.
> Fix automatic background area code

- device/globals/global_vm.gd
- device/project.godot
Broken down from my previous Pull request. This gives power to close Escoria by simply hitting the X button on a window.
I also renamed the project from 'prototype' to prototype Escoria, because I thought that sounded too generic.
> Quit by windows X button 3-17-18, and the project name is now "Prototype-Escoria"

- device/globals/dialog_instance.gd
- device/globals/item.gd
This PR contains two fixes for halts in the Daïza fork, and presumably other games which uses the same features.
- `device/globals/dialog_instance.gd`: Fix for animated dialogue boxes making the game unresponsive after disappearing
- `device/globals/item.gd`: Daïza has animations for items to play pick-up-sounds, etc., which I think is why we haven't noticed this one. When `p_notify` is null, it's not an instance of anything, which makes this check fail.
> Fix halt/crash discovered in Daïza fork

- doc/git_submodule.md
I documented how I got https://github.com/mjtorn/escoria-proto-submodule embedded this way.
Note that it is embedded in the https://github.com/mjtorn/escoria/tree/devel branch.
@fleskesvor is this in line with your thoughts as well?
> Documentation on how to use a git submodule

- device/demo/ui/action_menu.tscn
- device/globals/action_menu.gd
- device/globals/game.gd
This alters the action menu so it has to inherit from a Container class.
The reason behind it is that Node2D boundary calculation may or may not
be impossible, but Containers do it naturally.
It has also been said that you should always use Control nodes for UI,
so this feels like a more idiomatic approach.
Partially fixes #91
> Clamp action menu within viewport

- device/globals/dialog_player.gd
- device/globals/global_vm.gd
- device/globals/main.gd
- device/globals/music_player.gd
- device/globals/player.gd
- device/globals/sound.gd
- device/globals/vm_level.gd
- device/ui/main_menu.gd
I noticed that moving the camera from a corner to the center took a long time to start moving. After some digging around, it's because the camera would actually show they gray area outside the screen, which was properly fixed. Thus it started moving only after the camera though it was far enough from the bounds.
The solution is to check if the camera has been clamped down, and if so, reset its position. Without this fix it could take roughly a second for the camera to start moving, now it should take something like a delta-time between frames, like 30ms or whatever imperceptible.
This PR updates some pre-Godot3 code I found and renames (and comments on) some other stuff, so the functionality is hopefully clearer to someone who's never seen this before.
> Fix dealing with a clamped camera that tries to move

- .gitignore
- device/globals/esc_compile.gd
- device/globals/global_vm.gd
- device/globals/vm_level.gd
- doc/esc_reference.md
The goal of this PR is to properly support non-boolean globals so that it will eventually be possible to add counters (#66) and write more advanced comparisons in esc scripts.
This will require thorough testing, since there are many parts of the framework which rely on the return value from `vm.get_global()` being a global.
I have altered the autosave functionality to write the actual value of globals to the save script and also added comparisons using `eq [global] [value]` and `ne [global] [value]`. The latter does not perform any sanity checks yet, and should at the very least attempt to collect a quoted string containing comma(s).
I also haven't looked into regular save games yet, to make sure these changes don't cause any regressions.
> Support integer globals, including integer comparisons

- device/globals/game.gd
Prevent the tooltip text from showing up in the wrong place when mouse enters an item.
Close action menu and inventory (if it's implied to be supposed to be toggled by the presence of an action menu) when hitting escape to open the overlay menu.
> Trivial UI fixes

- device/globals/game.gd
Walking around in this area is horribly broken because `background_area.gd` uses viewport coordinates instead of "proper" coordinates like `TextureRect` and `background.gd` uses.
But at least this fixes the camera placement.
> Set camera limits properly when using background_area

- device/globals/game.gd
Investigating if #98 is still relevant (it is not, it should be closed), I noticed the player can walk while the action menu is opened.
This is problematic if the walking causes the background to scroll, and the fix is trivial.
Please merge!
> Stop player from walking when opening action menu

- device/globals/player.gd
Fix this problem that suddenly revealed itself.
```
SCRIPT ERROR: GDScript::reload: Compile Error: Identifier not found: vm
At: res://globals/player.gd:57.
ERROR: reload: Method/Function Failed, returning: ERR_COMPILATION_FAILED
At: modules/gdscript/gdscript.cpp:598.
```
It appears to have been introduced in 7336e54bd30ca1b696085e2dc5fdb7e78e6c4d19
but I haven't encountered this bug, so there may be a secondary cause.
> Restore `var vm` in `player.gd`

- device/globals/game.gd
This should have been in fcca54c7c0a404d0d7e1f765c5270e3b51e9b569
but the test case happened to line the tooltip properly, when
another later test case showed that it does have to be set by center.
> Fix tooltip mouse position by centering it

- device/globals/game.gd
- device/globals/inventory.gd
Exports a boolean `is_collapsible` on the inventory and uses `false` as default to make behaviour least surprising (even though many games will probably have this set to `true`).
Maybe a collapsible inventory should be opened when an item is picked up as well. It's possible to open the inventory from an esc script, but it is inconvenient to couple all pick_ups with explicit opening of the inventory.
> Make collapsible inventory configurable

- device/demo/actors/player/player.tscn
- device/demo/rooms/test/exit1.esc
- device/demo/rooms/test/exit2.esc
- device/demo/rooms/test/hotspot1.esc
- device/demo/rooms/test/test.tscn
- device/globals/background_area.gd
- device/globals/exit.gd
- device/globals/player.gd
- device/globals/trigger.gd
- doc/triggers-and-exits.md
Based on the splendid work by @fleskesvor on #124 and it's predecessor, I cooked this up.
I believe it ticks every box
It also enforces the player character to be a  `KinematicBody2D`, which was discussed on IRC to be an acceptable change, because certain external documentation is for 2.1 anyway.
Thoughts?
PS.
In the spirit of full disclosure, my https://github.com/mjtorn/escoria/tree/devel does not really work with this, but this may be due to overlapping `Control` (in this case `TextureRect`) nodes and these should be deprecated as soon as #121 is closed. When it is closed, I propose we deprecate support for non-`Area2D` hotspots and exits because only one _good_ way to do things is better than implicitly tons of ways.
> Hotspot and exit nodes

- device/globals/player.gd
This is useful when editing the player character. Without checking
for terrain, because player.gd is a tool script, the editor will
complain ceaselessly about missing a terrain.
> Allow not having a terrain in player.gd

- device/globals/hud.gd
I got annoyed by the amount of noise when trying to work on Spine animations, which requires a fair amount of temporary `printt()` debugging.
This is one of the main causes of useless prints, so I suggest we make it more relevant by not printing something that can be clearly seen in the game.
> Hide tooltip debug if there is no tooltip

- tools/lockit.gd
The script can be run with `godot --script ../lockit.gd` from the project root, or by using the `-s` short option, but not `-script` like the Floss Manuals tutorial says:
https://fr.flossmanuals.net/creating-point-and-click-games-with-escoria/i18n/
There's room for improvement here. Using a shell command to tidy up .lockit files doesn't seem very convenient. Maybe it would be better to support an in-place option like `sed` does. Ie. overwrite the .esc file but give an optional file extension that will be used to create a backup of the original.
> Fix localization helper script, lockit.gd

- device/demo/ui/confirm_popup.tscn
- device/ui/confirm_popup.gd
Fixes this issue mentioned in #142:
> While testing, I noticed that selecting "No" does not work, neither on "Quit" nor on "New Game" from an already running game. Moreover, the latter seems to leave the game in a very odd state when pressing "Yes" after first having pressed "No.
>
> As far as I can tell, this seems to always have been an issue in 3.0, while the tip of 2.1 works (with Godot 2.x), and it looks like it was an issue in 2.1 too. We might perform a bisect to check when the issue was introduced, but that will require a first pass with bisect to find the first commit which works with Godot v3.0.2 stable.
> Fix confirm popup to close on animation_finished

- device/project.godot
- device/ui/main_menu.gd
With this change, you don't need to commit a change into Escoria's
code to start your own game instead of the demo.
> Make the "boot" script a ProjectSetting

- device/globals/game.gd
I bumped into this while setting up things for the jam game. I have a path for an inventory but it's not created yet, which obviously leads into problems. That's when I noticed there's an `export var` to disable the inventory altogether!
Feels like a super-useful feature in early development and why not respect it in real games as well.
> Do not look for inventory if it's not enabled

- device/globals/inventory.gd
It occurred to me that we're most likely doing a scumm/daiza inventory, with so few items we don't need arrows. Why make them and hide them when we can make them optional?
> Drop the hard requirement on arrow_prev/arrow_next

- device/ui/confirm_popup.gd
Sometimes you want to use a `TextureRect` in your
confirmation popups, like if the artist wanted
to add decorations to the text.
This makes removing the `message` node possible
and replacing it with nodes named after the translation
identifiers.
> Allow textured content in confirmation popup

- device/globals/bg_music.gd
It turns out my initial assumption was wrong: The problem wasn't due to race conditions where state would be set before `bg_music` was available, but because when `vm` is cleared of state in https://github.com/godotengine/escoria/blob/master/device/globals/global_vm.gd#L662, `bg_music`, unlike `telon` never registers with `vm` again, because it wasn't in the "game" group.
When `demo/game.esc` or `quick_save.esc` are triggered by starting a new game or loading an autosave, ~`change_scene` is run, which caused the `bg_music` object to be removed. The reason why it's been working with the `:scene` command in my testing is that I've been running single scenes with background music from the editor, in which case the scene transition which caused `bg_music` to be erased didn't happen.~ **EDIT** …
> Fix bg_music on change_scene

- device/globals/player.gd
There were cases where the params_queue was cleared, with the side
effect that nothing happened until opening the action menu again.
@fleskesvor suggested this has been a problem with the verb menu
as well.
My investigations lead me to believe it has to do with disjointed
terrains or other unwalkable destinations that caused the queue
reset to happen too soon.
This should also be a somewhat straight-forward merge.
> Do not clear params_queue until walk_stop()

- device/globals/action_menu.gd
- device/globals/game.gd
- device/globals/hud.gd
The code was hiding the entire HUD because of the action menu,
though the comment pointed out it's the tooltip that needs to
be hidden.
This implements the proper code for it.
It also takes into account the tooltip on item mouse enter/exit.
> Fix action_menu show/hide to toggle only the tooltip

- device/globals/esc_compile.gd
- device/globals/game.gd
- device/globals/global_vm.gd
- device/globals/hud.gd
- device/globals/vm_level.gd
- docs/esc_reference.md
If your inventory is overlaid onto the game, and you want to
do camera-movement trickery, it's hard to set the scene so
the inventory doesn't get in the way.
It's also confusing for the brain because having an interactive
element feels like the game would be interactive during the
camera movement.
> ESC function to toggle HUD visibility

- device/globals/game.gd
This controls how close to the edge of the screen the camera
has to be before starting to move.
The default value of 0.2 is from Godot's own default values.
> Export camera drag margins in game.gd

- device/globals/item.gd
This is a critical yet trivial fix.
> Fix teleporting an item to use Godot 3.0 API

- device/demo/rooms/test/test.tscn
- device/globals/exit.gd
- device/globals/global_vm.gd
- device/globals/trigger.gd
With this commit, esc scripts can use `set_active` on triggers and exits. Using only visible for this is a much cleaner implementation than adding an extra `active` boolean as I originally did. Thanks to @fleskesvor for the idea!
> Toggle trigger/exit activity with `visible`

- device/globals/action_menu.gd
- device/globals/dialog_instance.gd
- device/globals/game.gd
- device/globals/hud.gd
Tooltips are hard due to how big they usually are, but clamping vertically is a good start and worth it.
Dialogs should never overflow. I think it's possible to mess with the camera so they still do, but in our jam game we see only great success.
Therefore this is one of those may-not-solve-world-hunger-but PRs. At least test it, please!
> Work on clamping UI elements

- device/demo/ui/inventory.tscn
- device/globals/dialog_player.gd
- device/globals/game.gd
- device/globals/game.tscn
- device/globals/game_am.tscn
- device/globals/main.tscn
- device/ui/hud.tscn
Anchor verb menu and inventory to the bottom left and right, respectively, to make the HUD less dependent on screen sizes.
The inventory takes up too much screen space in room2 and needs adjusting.
> HUD positioning

- device/globals/interactive.gd
- device/globals/item.gd
Also drops the `set_state()` call, because it had
side effects. Be sure to set the state first!
> Implement pose_scale for interactive and item

- device/globals/dialog_player.gd
- device/globals/game.tscn
- device/globals/game_am.tscn
- device/globals/main.tscn
- device/ui/hud.tscn
This reverts the change that placed the dialog player into a canvas layer in main.tscn, since unless position was fixed, dialog would be placed outside of the viewport in most cases, because of the difference between the scene size and the actual size of the viewport. There would have to be code in place to calculate position from the ratio between the two, but the previous solution is likely more predictable.
> Fix dialog

- device/globals/vm_level.gd
- docs/esc_reference.md
Because sched_event is so useful for testing, when you temporarily
set a game state in the room's event script, it should be possible
to test an object's `use inventory_item` events as well.
This commit brings that.
> Allow sched_event to have multi-word events

- device/globals/interactive.gd
- device/globals/item.gd
In interactive.gd, don't stop a playing animation, but let item.gd
do that. Having a stopped animation can lead to weird side effects,
which I can't explain, but where `state` is set though
`animation.get_current_animation()` returns `""`.
Now there's no need to call `animation.stop()` before setting a state,
so that's cleaner. I also cleaned up some of the `get_node("animation")`
mess because that's already bound to a variable anyway.
> Clean up item states, especially useful for NPCs

- device/demo/ui/dialog_default.tscn
- device/globals/dialog_instance.gd
- device/globals/dialog_player.gd
This reverts commit 28dea4d2ad5662dc2f27565c972965a68a79d1a2.
Because canvas layers didn't happen yet, a Container with the
dialog will be below regular items. My gut, and experimenting
with the ordering in the scene tree, tells me that this is
how it's supposed to work. Either you use Z or a separate
canvas layer.
> Revert "Move `dialog_default` out of demo as a `Container`"

- device/globals/main.gd
- device/project.godot
Although the documentation for
[Multiple Settings](http://docs.godotengine.org/en/3.0/tutorials/viewports/multiple_resolutions.html)
makes it sound like the `Expand` aspect ratio doesn't do
what we want, godotengine/godot#19912 states that this is the correct way.
~Further documentation may be warranted for the scene tree to
avoid having a clear-color bar at the top of a Retina game.~
~This commit does not yet address that documentation.~
It appears that it was a bug in Escoria that caused the problems with other aspect ratios.
> Settings for HiDPI/Retina, fix aspect ratio

- device/globals/interactive.gd
- device/globals/player.gd
This is because eg. Spine nodes, although not officially supported,
are inherited from CanvasItem. In fact, CanvasItem is what implements
light modulation, and `_find_sprites()` is used for nothing else,
it makes sense to apply the light map everywhere.
> Overload _find_sprites() to look for anything to modulate

- docs/spine.md
Because the duration patch has been merged to the Spine module's master and `spine-to-godot-scene.py` has been in its own repository for, like, six weeks.
> Update Spine documentation to reflect the current state of things

- device/globals/esc_compile.gd
It's annoying that depending on the command, inline comments may be ignored in later parsing and sometimes they cause side-effects when the second (or _n_ th) argument.
Just get rid of them up-front.
> Remove inline comments from ESC commands

- device/globals/game.gd
- docs/background.md
This should replace #213 as it doesn't try too hard to fix problems that are not relevant right now, but does add a note for the documentation.
I couldn't find a good place to add a documentation note about overlapping Area2Ds not working, too tired also to think, but I think a new GH issue is fine to document that until someone comes along to solve it.
Good to go?
> Discourage background having child nodes

- device/globals/game.gd
- device/globals/hud.gd
The action-menu code interacts with showing the tooltip,
and if an item doesn't have tooltip text, but the tooltip
is configured to have a background, an empty background
would show up without this.
It's annoying and fortunately fixed now.
> Show tooltip, as controlled by AM, only when it has text

- device/demo/rooms/room2/room.esc
- device/demo/rooms/room2/room.tscn
- device/demo/rooms/room2/zoom_in.esc
- device/globals/dialog_instance.gd
- device/globals/dialog_player.gd
- device/globals/game.tscn
- device/globals/game_am.tscn
- device/globals/global_vm.gd
This fixes at least three known issues:
1) Dialog not being clamped to viewport
1) Dialog not showing when telon is faded out
1) Dialog size being affected by zoom, obviously
I updated the demo as well, but it still looks ugly. I believe someone should take a look at it separately, like put some time into making all the positionings and alignments and such ok.
At least the demo shows that dialog size is not affected by zoom anymore, and that's the important part.
No documentation updates are required because the `dialog_layer` is in the `game*tscn` files. You break them, your fault.
> Implement dialog layer

- device/globals/action_menu.gd
- device/globals/dialog_instance.gd
- device/globals/game.gd
Another fast-track merge coming in!
I noticed that dialog wasn't clamped correctly when running the development version of Iron Sky: Cold War in full screen, 4k resolution, the room zoomed, and the game resolution as 1080. This would be the default way for the game, so it can't be broken.
I got upset at how broken everything is so I channeled that into really digging into the clamping code and found myself fixing all the problems!
This also renames the clamper function for the action menu as iirc @fleskesvor requested me to do if this code is ever touched again.
If you don't have a game to test this with, the next release of Iron Sky: A Lunar Adventure will demonstrate this very clearly. Currently the tooltip overflows off the right-hand side of the screen and the action menu opens way …
> Hopefully final clamping fixes

- device/globals/item.gd
- docs/items.md
This de-couples z-indexing from scaling. The use case is when
gfx artists draws a room with different "element items" as layers
in the same scale, and using the sizemap to get the z-index would
shrink the item.
The alternative to this is to debug what the scale factor is,
divide 1 by it, multiply by 100, scale that image separately,
and have it look ridiculously yet uselessly big in the editor.
Now it's possible to retain the artist's scales but also have
the player move behind the element item!
> Option for items to set only z-index from scalemap

- device/demo/actors/player/player.tscn
- device/globals/player.gd
- docs/setting_states.md
I succumbed to the death of #197 by duplicating and re-creating a ton of animations in favor of the existing API.
The amount of animations and tracks is closing in on bullshit, even though I was able to reuse some things by copying nodes and editing them.
Be that as it may, this should be merged instead of #197 because it retains the existing way, but also makes the code a bit clearer and suppresses a useless error from `get_node(costume)` when the costume doesn't exist.
> Refactor/streamline player's set_state for costumes

- device/demo/game.esc
- device/globals/esc_compile.gd
- device/globals/global_vm.gd
- device/globals/interactive.gd
- device/globals/item.gd
- device/globals/main.gd
- device/globals/player.gd
- device/globals/scene_base.gd
- device/globals/vm_level.gd
- docs/esc_reference.md
- docs/index.md
- docs/starting-a-game.md
I noticed an anomaly in A Lunar Adventure when continuing an old game.
Room 3 features an NPC going off to do his thing, but when loading, he stands at the start position.
This fixes the situation.
> Fix save load states

- device/globals/global_vm.gd
- device/globals/interactive.gd
- device/globals/player.gd
I accidentally found out that a save game could still contain negative degrees. This was due to getting the angle from `rad2deg()` without the special compensation used elsewhere.
That lead me to refactor the code for both interactives and the player into the VM.
I tested this extensively by:
* printing a ton of angle data out when walking the player
*  having an npc walk between whatever items were available
*  hacking a save game file with a `set_angle` and `turn_to` call for every angle.
The angles defined for both the player and the NPC are as follows:
```
const dir_angles = [0, 45, 90, 135, 180, 225, 270, 315, 360]
```
I also added some robustness in case someone tries to load a savegame with a broken angle value.
On top of that I fixed some setting of states (interactive) or playing …
> Even more angle code

- device/globals/dialog_dialog.gd
- device/globals/esc_compile.gd
- device/globals/game.gd
- device/globals/global_vm.gd
- device/globals/item.gd
- device/globals/player.gd
- device/globals/trigger.gd
- device/globals/vm_level.gd
This can't be properly split up so that anything works, and most of the changes are restoring the old function signatures.
The more important change is that the event table contains actual event instances.
> Megacommit to make all events EscoriaEvent

- device/globals/global_vm.gd
- device/globals/main.gd
- device/ui/main_menu.gd
- docs/esc_reference.md
This adds the `:setup` event with requisite changes to the VM.
The idea is that active NPCs, or the player, can be teleported to their correct places before the loaded
scene is ever shown.
This removes the problem of having the player (or NPC) "flash" in the wrong place before appearing in the correct one.
> Split load/run game to enable setup event

- device/default_bus_layout.tres
- device/globals/bg_music.tscn
- device/globals/dialog_instance.gd
- device/project.godot
- docs/music.md
This is the very least that should be done for audio control
It's not much, but it provides a foundation for further work (like looking into `sound.gd` etc) and there is a subtle yet audible effect in A Lunar Adventure. So this will be part of the next release, and I think I'll merge it soon enough.
Because you can just disable the behavior if you want and the documentation's there etc.
> Sound buses and volume

- device/demo/ui/dd_default.tscn
- device/globals/dialog_dialog.gd
A team member pointed out that the way I laid out and adjusted the dialog choices in A Lunar Adventure was horrible, even though he's not a Godot expert.
We figured out a better way, and here it is.
Basically it makes all the position-related numbers clearer to deal with and makes margins easier to add.
Hopefully @StraToN signs off on this because I'm swamped with other work :D
> Make dd_default structure clearer and more versatile

- device/globals/global_vm.gd
- device/globals/main.gd
This is because we encountered a bizarre camera alignment
bug when trying to pull off something cool with positioning
and zooming.
There is no obvious reason why this is the code that breaks,
unless it's related to the camera operations not being blocking.
Room changes are still quite fast with `queue_resource`, which
is the proper way to do it. Fixing the thread deadlock bug in
it would probably be the smarter way than trying to figure this
out.
Restored the relevant parts of b246a5761bfa6c80180e58ffbbf4910b014dddfc,
as it was reverted only to make the sequence free from conflicts.
Revert "Fix `not LEAVE_BLACK` behavior for new code"
This reverts commit 4137c1b61e65320274f75632ec87e63c702f4a1c.
Revert "Fake a :setup for scenes without one to keep up the flow of events"
This reverts …
> Revert faster setup code

- device/globals/camera.gd
- device/globals/esc_compile.gd
- device/globals/game.gd
- device/globals/game.tscn
- device/globals/game_am.tscn
- device/globals/global_vm.gd
- device/globals/vm_level.gd
- docs/esc_reference.md
Based on some discussion with @StraToN, some example code of his (merci!), and a Youtube video I don't have the link for, it makes sense to use `Tween` nodes instead of the calculated-step-based camera movement/zoom.
This PR reimplements the backend.
> Camera tween

- device/globals/esc_compile.gd
- device/globals/game.gd
- device/globals/global_vm.gd
- device/globals/inventory.gd
- device/globals/tooltip.gd
- device/globals/trigger.gd
- device/globals/vm_level.gd
- docs/esc_reference.md
The tooltip has turned out to be one of our most problematic components.
Moving to the signal-based architecture (though `trigger.gd` isn't quite there yet), there was a lot of duplication wrt the tooltip. It also occurred that `hover_object` was crazy overloaded and probably contributed to our problems.
What happens now is that the tooltip handles its own input and implements the `.update()` method for setting text based on the `global_vm` state, and thus also its visibility.
This simplified the signal handlers greatly, because now they can call `vm.hover_begin(obj)` and `vm.hover_end()` to set the state and those functions update the tooltip.
I decided to couple tooltip updating tightly, instead of having the signal handlers first set the state and then update the tooltip, because loose …
> Tooltip unification

- device/globals/action_menu.gd
- device/globals/dialog_instance.gd
- device/globals/dialog_player.gd
- device/globals/game.gd
- device/globals/global_vm.gd
- device/globals/hud.gd
- device/globals/inventory.gd
- device/globals/item.gd
- device/globals/main.gd
- device/globals/tooltip.gd
- device/globals/trigger.gd
To ease the frustration of #221 I started prototyping quickly with using z-indexes instead of a new `interact_layer` thing.
It's not the cleanest set of patches, but these aren't the best of times to focus on style.
As for z-indexes, them colliding should be rare enough that the behavior can be undefined by design (as it is with Godot itself).
Too bad it doesn't fix issues that seem to relate to events, like having the tooltip visible for a while after dialog if the cursor is moved or any of that. Maybe Godot is broken.
On the upside, it gets rid of some magic like the `overlapped_obj` hack, beside allowing areas to overlap. How a collapsible inventory interacts with the tooltip is also safely tucked away behind standard APIs.
The code has not been tested against the Lunar Adventure …
> Hover stack

- device/demo/rooms/outside/exit_hut2.esc
I guess it was a simple copy and paste error
> Actually move to Hut2 when entering it

- device/globals/dialog_instance.gd
- device/globals/global_vm.gd
- device/project.godot
fix the errors when running the main scene with godot 3.1.1 in #267
> for 3.1 branch - rename local variables that shadow globals

- README.md
Since the asset lib screenshots are stored in the repo, we can show them off in github as well ^_^
> Show off screenshots in the README

- addons/escoria-core/game/core-scripts/save_data/esc_save_manager.gd
- addons/escoria-core/game/escoria.gd
- game/ui/commons/options/options.gd
This PR fixes an issue with the settings loading workflow, that led the settings to be applied twice after loading. Second call was called too soon with data not loaded already.
> Fix settings being applied a second time with wrong data

- addons/escoria-core/game/core-scripts/esc_tooltip.gd
- addons/escoria-core/game/main.gd
- addons/escoria-ui-simplemouse/game.tscn
- addons/escoria-ui-simplemouse/inventory/inventory_ui.tscn
- addons/escoria-ui-simplemouse/tooltip/target_tooltip.tscn
- addons/escoria-ui-simplemouse/verbs_mouseicons.tscn
- docs/api/ESCTooltip.md
- docs/api/main.gd.md
- docs/esc.md
- project.godot
Fixes #302
I had to move the tooltip_node reference from ESCGame to ESCMain because of the loading order induced.
I am not sure this is right though so I'm open to suggestions.
> Fix tooltip_node wrong references

- addons/escoria-core/game/core-scripts/esc_game.gd
- addons/escoria-ui-9verbs/game.gd
Fixes #301 
This PR adds default behaviors in these functions:
- left_click_on_bg()
- right_click_on_bg()
- left_double_click_on_bg()
- left_click_on_item()
- right_click_on_item()
- left_double_click_on_item()
So that if these functions are *not* overridden in user's game.gd script, the default behavior will be used.
NB: if these function are overridden in user's game.gd script, these default behaviors will not be called (unless explicitly called using parent script call by adding a dot before the function: `.left_click_on_bg()`)
> Add default behaviors in ESCGame click handlers on BG and items.

- addons/escoria-core/game/core-scripts/behaviors/esc_movable.gd
- addons/escoria-core/game/core-scripts/esc_item.gd
- addons/escoria-ui-simplemouse/game.gd
- docs/api/ESCItem.md
Fixes #304
Allows user to name the Sprite/AnimatedSprite node in ESCItem any name.
> Removed hardcoded access to node named "sprite"

- addons/escoria-core/game/core-scripts/esc_item.gd
- docs/api/ESCItem.md
- game/characters/mark/mark.tscn
This fixes calls to the setter for animation_player when the player is running the game, which resulted in a crash.
> fix: FIxed non-editor call to _set_animation_player

- addons/escoria-core/game/core-scripts/behaviors/esc_movable.gd
- addons/escoria-core/game/core-scripts/esc/commands/say.gd
- addons/escoria-core/game/core-scripts/esc_item.gd
- game/rooms/room10/esc/button_accept_input_test.esc
This was causing ESC execution to hang after a say command because the state was at DIALOG and was not changed after the line is said.
- Also fixed connect() errors concerning the player being ready'd 2 times in certain cases, so trying to connect signals twice. That is a lot of checks!
> Fixed escoria.current_state when dialog line finishes

- addons/escoria-core/game/escoria.gd
- addons/escoria-core/game/main_scene.gd
I managed to put all scenes loadings in escoria.gd into _init() method. 
I also added a few checks so that a message is displayed when some mandatory Escoria Settings are not set.
> Move settings load and main menu loading in _init method

- addons/escoria-core/game/core-scripts/esc/commands/change_scene.gd
- addons/escoria-core/game/core-scripts/esc/commands/spawn.gd
- addons/escoria-core/game/escoria.gd
- addons/escoria-core/game/main_scene.gd
- addons/escoria-core/plugin.gd
- docs/api/SpawnCommand.md
- docs/api/escoria.gd.md
- docs/esc.md
- game/rooms/room08/esc/button_puzzle.esc
- game/start_game.esc
- game/ui/commons/main_menu/main_menu.gd
- project.godot
- Removed main_menu and pause_menu ProjectSettings, leaving this to gamedev
- Added a new "init" step in the start_script.esc to show the main menu
- Renamed "start" event in start_script.esc to "newgame" event
> Adds "name" parameter to ESC spawn command

- addons/escoria-core/game/core-scripts/esc/commands/camera_push.gd
- addons/escoria-core/game/core-scripts/esc/commands/camera_set_pos.gd
- addons/escoria-core/game/core-scripts/esc/commands/camera_set_target.gd
- addons/escoria-core/game/core-scripts/esc/commands/camera_set_zoom.gd
- addons/escoria-core/game/core-scripts/esc/commands/camera_set_zoom_height.gd
- addons/escoria-core/game/core-scripts/esc/commands/camera_shift.gd
- addons/escoria-core/game/core-scripts/esc/esc_object_manager.gd
- addons/escoria-core/game/core-scripts/esc_room.gd
- addons/escoria-core/game/main.gd
- addons/escoria-core/game/scenes/camera_player/camera.tscn
- addons/escoria-core/game/scenes/camera_player/esc_camera.gd
- addons/escoria-ui-9verbs/game.gd
- addons/escoria-ui-simplemouse/game.gd
- docs/api/ESCCamera.md
- docs/api/ESCObjectManager.md
- project.godot
> Removed hardcoded "camera" name reference and manual tween node camera

- README.md
- addons/escoria-core/game/core-scripts/esc_background.gd
- addons/escoria-core/game/core-scripts/esc_inventory_item.gd
- addons/escoria-core/game/escoria.gd
- addons/escoria-core/plugin.gd
- docs/api/ESCLogger.md
Fixes potential crash caused by escoria being null if load_settings() fails when it tries to log the error.
> Move Escoria settings load action out of init

- addons/escoria-dialog-simple/types/floating.gd
Now when a say() is trigged, the floating dialog player will follow the character it's attached to, positioning the dialog box at its "dialog_position" node position.
Can be tested in room10 using "Slide" button
> Fix: Make float dialog follow character

- addons/escoria-core/game/core-scripts/esc/commands/camera_push.gd
- addons/escoria-core/game/core-scripts/esc/commands/camera_shift.gd
- addons/escoria-core/game/core-scripts/esc_item.gd
- addons/escoria-core/game/core-scripts/esc_player.gd
- addons/escoria-core/game/scenes/camera_player/esc_camera.gd
- game/characters/mark/mark.tscn
- game/rooms/room07/room07.tscn
- project.godot
This optimizes the ESCCamera class in various aspects.
> feat: Optimized ESCCamera

- addons/escoria-core/game/core-scripts/esc/esc_compiler.gd
If an unknown command is detected on compile ESC, fail.
This was not triggering any error in ESCRoom because ESCRoom looks for `:setup` and `:ready` events only. Any other element would not be considered.
> Added a check on unknown ESC command at compilation time

- addons/escoria-core/game/core-scripts/esc_item.gd
- addons/escoria-core/game/inputs_manager.gd
- addons/escoria-ui-simplemouse/game.gd
- addons/escoria-ui-simplemouse/game.tscn
This fixes the input events noticed on Discord (inventory item hidden behind inventory panel, using unhandled_input in ESCItem as well). Additionally, it fixes the scroll wheel bug, @StraToN  mentioned.
> fix: Fixed more input events

- addons/escoria-ui-simplemouse/game.gd
Simplemouse only sets the verb if it is changed and thus it is set to nothing when an action finished and resets the verb
> fix: Resets the current verb after the action has finished

- addons/escoria-core/game/core-scripts/esc/commands/anim.gd
- addons/escoria-core/game/core-scripts/esc/commands/anim_block.gd
- addons/escoria-core/game/core-scripts/esc/commands/set_state.gd
- addons/escoria-core/game/core-scripts/esc_animation_player.gd
- project.godot
fixes godot-escoria/escoria-issues#56
fixes godot-escoria/escoria-issues#57
> feat: Optimizes animation commands

- addons/escoria-core/game/core-scripts/log/esc_logger.gd
Asserts were removed so the game would not stop to debugger.
Note: asserts are not processed in release mode so the game will not hang in other modes than debug.
> Re-add removed assert(false)

- addons/escoria-core/game/core-scripts/esc_game.gd
- addons/escoria-core/game/core-scripts/log/esc_logger.gd
- addons/escoria-core/game/main.gd
- addons/escoria-ui-9verbs/game.gd
- addons/escoria-ui-simplemouse/game.gd
Also overriding the show_crash_popup() function is not mandatory
> Adds default crash popup, if game.gd doesn't reimplement it

- addons/escoria-core/game/core-scripts/esc/commands/change_scene.gd
- addons/escoria-core/game/core-scripts/esc_room.gd
Recent change in ESC_LAST_SCENE so that it was set too early resulted in this variable containing the current room id after the room was loaded, instead of the last one.
This "incorrect" change was necessary though for the transitions management between change_scene and ESCRoom.
As a side issue, I had to make ESCRoom manage unpause if in certain cases (happening when accessing room14 using room selector: in this case ESC_LAST_SCENE is null ; using 4th button for the first time in this case will have to deal with this).
Problem was that, in this case, change_scene does not play automatic transition, so the ESCRoom does, and it will now have to hide main/pause menus.
> Reverted setting ESC_LAST_SCENE too early in ESCRoom

- addons/escoria-core/game/core-scripts/behaviors/esc_movable.gd
- addons/escoria-core/game/core-scripts/esc_item.gd
- addons/escoria-core/game/core-scripts/esc_player.gd
- addons/escoria-core/game/core-scripts/esc_room.gd
- addons/escoria-ui-9verbs/verbs_menu.gd
Fix player sprite not showing correct idle animation after animations change in room switch
Remove some more error outputs (godot-escoria/escoria-issues#64)
Fix verbs menu button selection when input mode is not all
> fix: Fixes smaller things

- addons/escoria-core/game/core-scripts/esc/types/esc_condition.gd
- addons/escoria-core/game/core-scripts/esc_animation_player.gd
- addons/escoria-core/game/core-scripts/esc_controller.gd
- addons/escoria-core/game/core-scripts/esc_game.gd
- addons/escoria-core/game/core-scripts/esc_item.gd
- addons/escoria-core/game/escoria.gd
- addons/escoria-core/plugin.gd
- addons/escoria-dialog-simple/plugin.gd
- addons/escoria-ui-9verbs/game.gd
- addons/escoria-ui-9verbs/plugin.gd
- addons/escoria-ui-simplemouse/game.gd
- addons/escoria-ui-simplemouse/plugin.gd
- project.godot
This fixes another error message of godot-escoria/escoria-issues#64
This optimizes how UI and dialog managers register themselves with Escoria
This fixes another "character is at position, but action still isn't carried out"
This fixes click bubbling down to multiple items triggering different actions
This removes the "tooltip follows focus" setting because it solemly was a simplemouse feature
This optimizes the registering of settings
> feat: Several fixes and optimizations

- addons/escoria-core/game/escoria.gd
- addons/escoria-core/game/scenes/dialogs/esc_dialog_player.gd
- addons/escoria-core/game/scenes/sound/esc_music_player.gd
- addons/escoria-core/game/scenes/sound/esc_sound_player.gd
- addons/escoria-core/game/scenes/sound/esc_speech_player.gd
- addons/escoria-dialog-simple/esc_dialog_simple.gd
- addons/escoria-dialog-simple/types/avatar.gd
- addons/escoria-dialog-simple/types/floating.gd
- addons/escoria-dialog-simple/types/floating.tscn
- addons/escoria-ui-9verbs/game.tscn
- addons/escoria-ui-simplemouse/game.tscn
Fixes a blocking issue happening when pausing the game (ESC key) while a say line was ongoing: dialog line was yielding for say_finished signal, thus blocking pause menu
> Fix: makes dialog players pausable by removing yields

- addons/escoria-core/game/core-scripts/esc/commands/change_scene.gd
- addons/escoria-core/game/core-scripts/esc/esc_globals_manager.gd
- addons/escoria-core/game/core-scripts/esc/esc_room_manager.gd
- addons/escoria-core/game/core-scripts/esc_room.gd
- addons/escoria-core/game/escoria.gd
- addons/escoria-core/ui_library/tools/room_select/room_select.gd
- game/rooms/room15/esc/right_exit.esc
- game/rooms/room16/background.tscn
- game/rooms/room16/esc/current_scene_button.esc
- game/rooms/room16/esc/left_exit.esc
- game/rooms/room16/esc/room16.esc
- game/rooms/room16/room16.tscn
- project.godot
New reserved global to hold current scene global ID to allow for flexibility in ESC scripts.
Also refactor reserved globals' handling for rooms with addition of ESCRoomManager and the elimination of string literals across multiple files. Allows for less chance of accidental errors as opposed to using string literals everywhere. As well, this encapsulates room-specific reserved globals and will serve as the basis for more room-specific behaviour management.
> feat: add esc_current_scene reserved global

- addons/escoria-core/game/core-scripts/esc_item.gd
… the upper limit check for the speaking index
> fix: set a proper guard in case of no speaking animations

- .github/CODEOWNERS
This sets the codeowners of this repo, which results in us being added as default reviewers. Once this is merged, I'll set the minimum reviewer count for PRs to 2, so we have the discussed quorum.
> chore: Create a codeowners file for default PR reviewers

- addons/escoria-core/game/core-scripts/esc_item.gd
fix: This is to fix #496. The current code doesn't work as "animations" doesn't have a "speaks" parameter when "animations" is null.
> fix: animations doesnt have a speaks parameter when it is null

- addons/escoria-ui-simplemouse/game.gd
Apparently this was accidentally introduced in
99dc1e01106ce651d1b78ae574cca9d0202c48b1. This commit
removes it and consolidates one clause into the existing
conditional check.
> Remove non-existent escoria.action_to_string() function.

- addons/escoria-core/game/core-scripts/esc/esc_room_manager.gd
When creating a new `ESCRoom`, there was a bug where it was not possible
to transition into the room if the room's `esc_script` was not set.
Apparently, `_perform_script_events()` would bail out early when
`room.esc_script` is falsy, which seems to be why the transition does
not happen.
Perhaps this defensive check was necessary at one time, but that does
not appear to be the case today because the only code that reads
`room.esc_script` in this file is within the `_run_script_event()`
function, which does its own defensive check for `room.esc_script`. As
such, it appears that we can let the rest of `_perform_script_events()`
do its thing even when `room.esc_script` is falsy (i.e., `""`).
> fix: enable transition to ESCRoom even if esc_script is not set

- addons/escoria-core/game/core-scripts/esc/commands/camera_set_pos.gd
- addons/escoria-core/game/core-scripts/esc/commands/camera_set_target.gd
- addons/escoria-core/game/scenes/camera_player/esc_camera.gd
@StraToN @dploeger @BHSDuncan Fixes https://github.com/godot-escoria/escoria-issues/issues/136.
This makes all the camera commands consistent (i.e. using time instead of speed)
> fix: camera commands to use time instead of speed

- .gitignore
For example, this makes it easier to do a bunch of testing
to `escoria-ui-simplemouse` without making a temporary change
to `project.godot` because you can create `override.cfg` with
the following:
```
[escoria]
ui/game_scene="res://addons/escoria-ui-simplemouse/game.tscn"
```
> chore: add override.cfg to .gitignore

- addons/escoria-core/game/core-scripts/esc_item.gd
Fixes https://github.com/godot-escoria/escoria-issues/issues/147
> fix: ESCItem that is a trigger should not capture input events

- addons/escoria-core/game/core-scripts/esc/types/esc_command_argument_descriptor.gd
The current error messages are not as developer friendly as they could be. This addresses that as per #108 
It does not however fix the other fault mentioned in that issue where the filename is not mentioned as part of the error message.
Before:
2022-2-22T173259 (E)	Errors in file Argument type did not match descriptor for command "camera_shift"
Argument 1  is of type 4. Expected 2,3
After:
2022-2-22T173259 (E)	Errors in file Argument type did not match descriptor for command "camera_shift"
Argument 1 ("-100") is of type TYPE_STRING. Expected [TYPE_INT|TYPE_REAL]
FYI @dploeger @StraToN @BHSDuncan
> feat: more useful error messages

- addons/escoria-core/game/core-scripts/esc/types/esc_command_argument_descriptor.gd
While looking into [issue 139](https://github.com/godot-escoria/escoria-issues/issues/139) I came across a bug. The validate command can't print the error message it's supposed to. The "%s" that is supposed to print the "arguments" array fails. The error message given is "not enough arguments for format string in operator '%'.
Test this by just changing the arguments.size comparison (line 58, esc_command_argument_descriptor.gd) from
```
if arguments.size() < self.min_args:
```
to
```
if arguments.size() < 50:
```
> fix: parameter validation function cant print necessary arrays on error

- addons/escoria-core/game/core-scripts/esc_item.gd
@StraToN @dploeger @dploeger FYI 
I couldn't find any reason you needed to set camera_node in ESCItem to get push commands to work. As far as I can tell it's not necessary so I've removed it. If I'm wrong and it ends up that it's needed, the camera node setting in ESCItem (what it's for and what you set it to) needs to be documented.
> refactor: remove redundant check for camera node

- addons/escoria-ui-9verbs/game.gd
- addons/escoria-ui-9verbs/verbs_menu.gd
- addons/escoria-ui-simplemouse/game.gd
Review stack (1/3) [Next](https://github.com/godot-escoria/escoria-demo-game/pull/503)
* :triangular_flag_on_post: #521
* https://github.com/godot-escoria/escoria-demo-game/pull/521/commits/df8299fc7f1940dce3a68985c0928d1ec13de644 refactor: remove trailing whitespace from all .gd files
* #503
* #518
> refactor: remove trailing whitespace from all .gd files

- addons/escoria-core/game/core-scripts/esc/esc_compiler.gd
fix: Automatically remove trailing whitespace when parsing scripts to avoid needing to change all regular expressions separately
fixes https://github.com/godot-escoria/escoria-issues/issues/172
> fix: Automatically remove trailing whitespace when parsing scripts

- game/rooms/room01/room01.tscn
- game/rooms/room02/room02.tscn
- game/rooms/room03/room03.tscn
- game/rooms/room08/room08.tscn
- game/rooms/room09/room09.tscn
- game/rooms/room10/room10.tscn
- game/rooms/room11/room11.tscn
- game/rooms/room12/room12.tscn
- game/rooms/room13/room13.tscn
- game/rooms/room14/room14.tscn
- game/rooms/room15/room15.tscn
- game/rooms/room16/room16.tscn
- game/rooms/room17/room17.tscn
fix: Updated camera x limit to 1280 to match the background graphics in each room
I've left room5 and 6 out as they have separate PRs.
> fix: Updated camera x limit to 1280 to match the background graphics in each room

- game/rooms/room07/room07.tscn
I'd put the player start in the right hand side of the room while testing and didn't move it back. Now it's back where the user can immediately read the level description.
> fix: player_start needed to be where the level description is

- addons/escoria-core/game/core-scripts/esc_item.gd
- addons/escoria-core/game/inputs_manager.gd
- addons/escoria-ui-simplemouse/game.gd
Review stack (3/3) [Prev](https://github.com/godot-escoria/escoria-demo-game/pull/503)
* #521
* #503
* :triangular_flag_on_post: #518
* https://github.com/godot-escoria/escoria-demo-game/pull/518/commits/fd73dfa7197282bf3b18e047989cb64996fc143c feat: add gamepad support to escoria-ui-simplemouse
---
Updates escoria-ui-simplemouse to demonstrate basic gamepad support.
Addresses https://github.com/godot-escoria/escoria-issues/issues/101.
> feat: add gamepad support to escoria-ui-simplemouse

- .gitignore
- addons/escoria-core/default_bus_layout.tres
Apparently Godot stores the settings of the audio bus layout in the editor locally somewhere. We set "default audio bus layout" to the resource file in this commit and when starting up the auditor, Godot loads the bus layout setting and applies it to the resource file.
This is just to reset the layout to 0db for each channel. If any dev should've changed the layout in their editor, they should reset their layout as well.
> fix: Reset audio bus layout

- addons/escoria-core/game/core-scripts/esc/commands/camera_push.gd
I encountered a small crash in room 6 (lift room) while using the elevator.
Fixes the crash caused by out of bounds of array.
> Fix: out of bounds exception in camera_push

- addons/escoria-core/game/core-scripts/esc_exit.gd
- addons/escoria-core/game/core-scripts/esc_item.gd
Clarifying when to use ESCexit instead of ESCitem.
> feat: Updated exit documentation

- addons/escoria-core/game/core-scripts/esc/commands/rand_global.gd
rand_global required a pre-existing variable to use due to the validation commands. These were removed after discussion with @StraToN. 
The documentation also listed both "exclusive" and "inclusive" for the random number range. This was standardised to "inclusive" and the code modified to suit.
> fix: rand_global fixes

- addons/escoria-core/game/core-scripts/log/esc_logger.gd
- game/rooms/room03/esc/button.esc
This allows debug messages to print the contents of globals. Globals are indicated by brace symbols " { } "
```
debug "r3_button_broken is currently {r3_button_broken}"
```
I have added the function to resolve globals to all debug levels (info, warning etc) but due to [bug 219](https://github.com/godot-escoria/escoria-issues/issues/219) I can't test other debug levels so I'm not sure if the behavior is correct.
If everyone's happy with the "{ global }" notation, I'll need to update the documentation in the documentation repo. 
The alternative is Godot string notation
```
debug "Name %s is %d years old", name, age
```
But I don't know how to extend the parser to cope with this so I went with what I knew how to code :D 
Output for valid global
```
2022-4-3T11331 (D)	Running command debug …
```
> feat: Added ability to print globals as part of debug messages

- addons/escoria-core/game/core-scripts/esc/commands/say.gd
- game/rooms/room04/esc/left_exit.esc
- game/rooms/room04/esc/room04.esc
- game/rooms/room04/room04.tscn
Adds global interpolation for say command. Globals are indicated by putting them within braces.
This format is also suggested for debug messages as per [561](https://github.com/godot-escoria/escoria-demo-game/pull/561)
```
say player "You have looked at the doorway {r4_door_look_count} times"
```
> feat: Add global interpolation for say command

- addons/escoria-core/game/core-scripts/esc/commands/print.gd
- game/rooms/room10/esc/room10.esc
The current debug command is restricted to "log level = debug".  This means that you can't use it to do your own debugging if you use a different log level.
This PR adds a print command. It needs to be a separate command to debug as debug is used by the engine to print all the internal engine state. As a result, if debug was allowed to print at any log level, you would end up with engine debugging messages even at "info" level.
> feat: Added print command to print output at any debug level

- addons/escoria-core/game/core-scripts/esc/commands/inventory_add.gd
- addons/escoria-core/game/core-scripts/esc/esc_globals_manager.gd
Fixes https://github.com/godot-escoria/escoria-issues/issues/153
> Fix: Avoid globals starting with 'i/'

- addons/escoria-core/game/core-scripts/esc/esc_action_manager.gd
- addons/escoria-core/game/core-scripts/esc_item.gd
Prints a warning if there is more than one ESCLocation (position2d) as a child of an ESCITem
> feat: Added warning message when multiple locations found for an item

- game/rooms/room01/room01.tscn
- game/rooms/room04/room04.tscn
- game/rooms/room05/room05.tscn
- game/rooms/room06/room06.tscn
- game/rooms/room07/room07.tscn
- game/rooms/room08/room08.tscn
- game/rooms/room09/room09.tscn
- game/rooms/room10/room10.tscn
- game/rooms/room11/room11.tscn
- game/rooms/room12/room12.tscn
- game/rooms/room13/room13.tscn
- game/rooms/room14/room14.tscn
- game/rooms/room15/room15.tscn
- game/rooms/room16/room16.tscn
- game/rooms/room17/room17.tscn
When transitioning, the nodes that I'd created in the rooms of "node" type have issues with being hidden/shown at the wrong time. This fix is to change them to Node2D which supports a visibility setting.
> fix: correct change nodes of node type to node2d type to fix transitions bug

- addons/escoria-core/game/core-scripts/esc/commands/print.gd
- addons/escoria-core/game/core-scripts/esc/commands/say.gd
- addons/escoria-core/game/core-scripts/esc/esc_event_manager.gd
- addons/escoria-core/game/core-scripts/log/esc_logger.gd
- addons/escoria-core/game/scenes/esc_prompt/esc_prompt_popup.gd
- game/rooms/room03/esc/button.esc
- Removed "debug" as it's been replaced by print (which works at all debug levels)
- Fixed issue where print didn't interpolate the globals in the text in all instances
- Updated the debug console to use print over debug. Compared output in the debug window when using print vs debug and the 11 debug output lines are identical (repacing everywhere that says "debug" with "print")
- Deduplicated the replace_globals function
Fixes : https://github.com/godot-escoria/escoria-issues/issues/221
> refactor: remove deprecated debug command

- addons/escoria-core/game/scenes/dialogs/esc_dialog_player.gd
- game/rooms/room01/esc/wall_item_popupdialog.esc
An underlying bug also existed where multiple `say` commands in the same event caused an issue if one of the subsequent `say` commands in said event used an invalid dialog player type. It looks like re-using the same player as such would throw an error with trying to connect the same signal (despite being a 'oneshot'), but this could be either because of a race condition or that the manager was being marked for deletion and not processed in a timely fashion.
> fix: incorrect dialog player type

- addons/escoria-core/plugin.gd
This fix removes all direct calls to "escoria" singleton that blocks re-enabling the plugin after it was disabled (because the singleton was removed).
Replaced by using `get_node("escoria")` instead.
Also added implementions of `_enable_plugin()` and `_disable_plugin()` virtual functions from EditorPlugin class.
> Fix: removed calls to inexisting "escoria" singleton after plugin disbld

- addons/escoria-core/game/core-scripts/esc/esc_room_manager.gd
- game/rooms/room02/room02.tscn
@BHSDuncan has already closed this issue as the bug was a small room misconfiguration, however on reflection, I thought it would be good to fix as it is easy to detect and flag to the developer. If we can do it in the demo levels, they can do it in the real world.
If the character is at the edge of a terrain, and you try to make them walk further, the walk_stop command will reset their location by the room offset amount (ignoring any terrains and repositioning them by an addition room's pixel offset amount each time you click).
https://github.com/godot-escoria/escoria-issues/issues/218
> fix: Enforce rooms to be located at (0,0)

- addons/escoria-core/game/core-scripts/esc/esc_action_manager.gd
- addons/escoria-core/game/core-scripts/esc/esc_event_manager.gd
- addons/escoria-core/game/core-scripts/esc/esc_room_manager.gd
- addons/escoria-core/game/core-scripts/esc_game.gd
- addons/escoria-core/game/escoria.gd
- addons/escoria-core/game/main.gd
- addons/escoria-core/game/scenes/transitions/esc_transition_player.gd
- addons/escoria-ui-9verbs/game.gd
- addons/escoria-ui-9verbs/game.tscn
- addons/escoria-ui-keyboard-9verbs/game.tscn
- addons/escoria-ui-simplemouse/game.tscn
- game/rooms/intro/esc/intro.esc
Also does the following:
- Eliminates UI flicker during game startup
- Eliminates menu disappearing resulting in flicker of previous scene when transitioning to first scene during `:newgame`
These should be tested against saving and loading games when the system is back in working order.
> fix: allows for transitions to be disabled during :init event

- addons/escoria-core/game/core-scripts/esc_game.gd
- addons/escoria-core/game/escoria.gd
- addons/escoria-core/game/main.gd
- addons/escoria-ui-simplemouse/game.gd
Note: this bug happens on Godot 3.4.4, using simple-mouse plugin.
Fixes a crash happening when game scene was receiving inputs while changing the scene.
> Fix: disable ESCGame inputs until signal room_ready is emitted

- game/rooms/room10/esc/button_turn_to.esc
- game/rooms/room10/room10.tscn
fixes : https://github.com/godot-escoria/escoria-issues/issues/168
The description on that issue is old. We've since clarified how turn_to works in the documentation, so the room has been fixed to match.
> fix: Fix #168 as turn to in room 10 didn't work correctly

- game/rooms/room10/esc/button_accept_input_test.esc
As it is, it throws the following error
```
ESC 2022-06-05T00:29:54 (D)    Running command say with parameters [player, "Ha! Now you can't even skip this text!", avatar_dialog_player]     
ESC 2022-06-05T00:29:54 (E)    Errors in file esc_dialog_player.gd:say
No dialog manager supports the type avatar_dialog_player
```
Orion ("Dev Orion" on Discord, I'm not sure here on github) pointed out on Discord it's likely a typo. This is the change discussed there, which I tested and fixes the issue.
> fix: Fixes typo in say statement

- addons/escoria-core/plugin.gd
Downside: is now displayed UNDER project settings window
> Fix: escoria-core warning plugin has godot editor style

- addons/escoria-ui-simplemouse/game.gd
Simplemouse - inventory not showing, and options menu showing when it shouldn't when you pause the game.
Fixes https://github.com/godot-escoria/escoria-issues/issues/283
> issue 283 - make inventory appear when running via f5. Hide options menu when pausing game.

- addons/escoria-core/game/core-scripts/esc/esc_action_manager.gd
- addons/escoria-core/game/core-scripts/esc/esc_event_manager.gd
I'm not sure if this is the right way to solve this problem with scheduling events etc, but it looked right to me and worked for my testing.
To test, take an item (eg. the left hand painting in room 1) and move its related ESCLocation out of the navigation polygon.
Standard behavior is a warning debug message.
If you add a "cant_reach" event to the object's script, this will fire. e.g.
```
:cant_reach
say player "Sorry, I can't reach the painting."
```
Fixes https://github.com/godot-escoria/escoria-issues/issues/165
> Issue 165 - no indication when destination is unreachable

- addons/escoria-core/game/core-scripts/esc/commands/set_angle.gd
Support for both real and int to be accepted for the angle for the player to face, and for the amount of time the character will face each intervening direction as they turn. Currently only ints are allowed for direction, and real for wait time.
Questions for discussion
1) Duration is expected to be a real, but I used an int. This is easily fixed by just changing the validate function to 
[TYPE_STRING,  TYPE_INT,  [TYPE_REAL, TYPE_INT]]. 
The second parmeter is the angle you want the player to face. I've tested and this also works as a real, i.e.
[TYPE_STRING,  [TYPE_REAL, TYPE_INT],  [TYPE_REAL, TYPE_INT]],
So can anyone see a reason the developer shouldn't be allowed to specify an angle as a real? I can't see anyone ever needing it, but at least it wouldn't break things if they …
> fix: Support for both int and real for set_angle command

- addons/escoria-wizard/RoomCreator.gd
- addons/escoria-wizard/plugin.gd
I was using the "room_selector_room_dir" project setting as the path to the base folder in your project for rooms. This created a dependency on the room selector which isn't a wise idea. 
This change moves the setting to its own dedicated settings page which makes the plugin more stand-alone.
> fix: Move wizard path to rooms to its own Godot setting

- addons/escoria-core/game/core-scripts/esc/commands/anim.gd
- addons/escoria-core/game/core-scripts/esc/commands/anim_block.gd
- addons/escoria-core/game/core-scripts/esc/commands/camera_push.gd
- addons/escoria-core/game/core-scripts/esc/commands/camera_set_limits.gd
- addons/escoria-core/game/core-scripts/esc/commands/camera_set_pos.gd
- addons/escoria-core/game/core-scripts/esc/commands/camera_set_target.gd
- addons/escoria-core/game/core-scripts/esc/commands/camera_set_zoom.gd
- addons/escoria-core/game/core-scripts/esc/commands/camera_set_zoom_height.gd
- addons/escoria-core/game/core-scripts/esc/commands/camera_shift.gd
- addons/escoria-core/game/core-scripts/esc/commands/change_scene.gd
- addons/escoria-core/game/core-scripts/esc/commands/custom.gd
- addons/escoria-core/game/core-scripts/esc/commands/say.gd
- addons/escoria-core/game/core-scripts/esc/commands/turn_to.gd
- addons/escoria-core/game/core-scripts/esc/types/esc_base_command.gd
Updated version of previous PR to include changing all messages for "interrupt() function not implemented." from warning to debug level.
I'm not sure if the message in addons/escoria-core/game/core-scripts/esc/types/esc_base_command.gd should be a stronger warning level (error maybe?)
> fix: interrupt not implemented messages changed to debug from warn

- addons/escoria-wizard/CharacterCreator.tscn
- addons/escoria-wizard/ItemCreator.tscn
- addons/escoria-wizard/RoomCreator.gd
- addons/escoria-wizard/escoria_wizard.gd
- addons/escoria-wizard/item_creator.gd
* Added ability to change path for inventory items with a button
* Handle error when the inventory item destination folder doesn't exist
* Fixed bug where leaving the item creator with inventory item selected then going back would leave the interface with the inventory button selected, but everything else about the item interface would be for non-inventory objects.
* Minor update to a help message in the character creator
> Fix: Wizard - verify that inventory items are written to valid folders

- addons/escoria-core/game/core-scripts/esc/commands/say.gd
- addons/escoria-core/game/core-scripts/save_data/esc_save_manager.gd
- addons/escoria-core/game/core-scripts/save_data/esc_savesettings.gd
- addons/escoria-core/game/core-scripts/save_data/esc_settings_manager.gd
- addons/escoria-core/game/esc_project_settings_manager.gd
- addons/escoria-core/plugin.gd
- addons/escoria-dialog-simple/plugin.gd
- addons/escoria-wizard/plugin.gd
This PR is to separate dialog settings from core to make the dialog plugin standalone.
This also fixes the error messages seen when disabling and enabling core relating to info.type missing in the call in esc_project_settings_manager
> fix: Removing dialog settings from core

- addons/escoria-core/game/scenes/camera_player/esc_camera.gd
This is to fix the bug where if you open a room (e.g. room 4) and go into room 3, then quit the game by force closing the window, you get the error:
E 0:00:05.946   remove_child: Parameter "p_child" is null.
<C++ Source>  scene/main/node.cpp:1308 @ remove_child()
<Stack Trace> esc_camera.gd:27 @ _exit_tree()
Only seems to show up with simplemouse, 9 verb didn't show it.
> fix: Fix p_child is null exit on quit

- addons/escoria-core/game/core-scripts/esc_item.gd
This error fires when there's no path, so removing the reference to the path from the output
> fix: Correct error message for missing animation player

- addons/escoria-core/game/core-scripts/esc_item.gd
Without this line being removed, during a conversation, stop talking gets called by both :
and
The result of this is that this code is called twice
```
if animations.speaks[_movable.last_dir].mirrored \
and not _movable.is_mirrored:
_sprite_node.scale.x *= -1
```
Which, when you have a mirrored talking animation, means that the character gets turned to face the wrong way when they finish talking.
> fix: Remove call to stop dialog to correct player mirroring

- addons/escoria-core/game/core-scripts/esc/commands/turn_to.gd
The turn 'A' towards 'B' error message was saying can't turn 'A' towards 'A'. Took the opportunity to make the error message more user-friendly.
> Fix: wrong argument passed in turn_to error message

- addons/escoria-core/game/core-scripts/save_data/esc_savesettings.gd
- addons/escoria-core/game/core-scripts/save_data/esc_settings_manager.gd
- addons/escoria-core/ui_library/menus/options/options.gd
- addons/escoria-core/ui_library/menus/options/options.tscn
- game/translations/main_menu.csv
I'm unsure if I should have used `set_pressed` instead of `set_pressed_no_signal` in `addons/escoria-core/ui_library/menus/options/options.gd` line 64.
> feat: add fullscreen option in options menu

- addons/escoria-core/game/scenes/dialogs/state_machine/dialog_say.gd
- addons/escoria-dialog-simple/esc_dialo_simple_settings.gd
- addons/escoria-dialog-simple/esc_dialog_simple.gd
- addons/escoria-dialog-simple/esc_dialog_simple_settings.gd
- addons/escoria-dialog-simple/plugin.gd
- addons/escoria-dialog-simple/types/avatar.gd
- addons/escoria-dialog-simple/types/floating.gd
- project.godot
There's a problem when you try to export game and launch it, you'll get a grey screen. In the log there's errors about  `Unknown class: "EditorPlugin"` presumably because editor classes aren't exported. The problem is that `escoria-dialog-simple` plugin exports it's class name to other scripts which get settings via it. So I've moved settings to separate script that extends `Resource` same as `ESCProjectSettingsManager`. It fixes the problem.
> move dialog settings to another script to fix exported game issues

- addons/escoria-core/game/escoria.tscn
- addons/escoria-dialog-simple/types/avatar.gd
Fixes https://github.com/godot-escoria/escoria-issues/issues/356
Fixes https://github.com/godot-escoria/escoria-issues/issues/352
> fix: allows avatar (popup) dialogs to resume after pausing is concludes; also prevents unnecessary input from being registered during pauses

- .github/workflows/apidoc.yml
- .github/workflows/fanout.yml
- .github/workflows/prerelease.yml
The actual "fix" involved resetting those fanout repos that used 'core' as there was a commit from mid-2022 that seemed not to exist in the demo game repo.
Also updates the deployment token used in other GH Actions jobs.
> Fanout fix

- addons/escoria-core/game/esc_inputs_manager.gd
Fixed by not emitting a signal stating hover_stack change when the item was not in the hover_stack
> Fix crash in room19

- addons/escoria-core/game/core-scripts/esc_item.gd
If ColorN is used, for some reason, the dialog color is reset to white (ignoring any changes made by the developer) when the game is started. The equivalent "color" command doesn't show this bug.
> fix: addresses issue where using ColorN for dialog_color is buggy

- addons/escoria-core/game/core-scripts/esc/esc_action_manager.gd
When an ESCItem is marked as a trigger, and you have a missing trigger_in or trigger_out event in its script, the game would crash when it tried to execute the event. This fixes this problem.
> fix: Stops crash on missing trigger event

- addons/escoria-core/game/core-scripts/esc/types/esc_command_argument_descriptor.gd
- addons/escoria-core/game/esc_inputs_manager.gd
- addons/escoria-core/game/esc_logger.gd
- addons/escoria-core/game/scenes/esc_prompt/esc_prompt_popup.gd
- addons/escoria-core/game/scenes/esc_prompt/esc_prompt_popup.tscn
- scroll down the terminal when a command is entered
- new: navigate through commands history (20 last commands max) using up and left arrow keys
- fix: do not crash when the entered command returned an error (either because the command doesn't exist or because its parameters validation failed) and show the error instead
> Improve ESC prompt F2

- addons/escoria-wizard/CharacterCreator.gd
When creating a new character using the Escoria Wizard, the floating dialogue appears only on the top of the screen, regardless of the position of the Dialogue Location set in the character scene.
The Wizard creates a instance of a ESCLocation class for the dialog_position:
Whereas the floating dialog requires an ESCDialogLocation class (addons/escoria-dialog-simple/types/floating.gd):
> fixed dialogue appearing only on top of the screen

- addons/escoria-core/game/core-scripts/save_data/esc_settings_manager.gd
- addons/escoria-core/game/esc_project_settings_manager.gd
- addons/escoria-core/plugin.gd
I just did a clean install of Godot 4.3 followed by a fresh clone of https://github.com/godot-escoria/escoria-demo-game and starting the demo game crashed at startup because the setting `display/window/size/fullscreen` defined here was not set:
https://github.com/godot-escoria/escoria-demo-game/blob/eb9f5cb0edda010df879541810eb7802bd68eccf/addons/escoria-core/game/esc_project_settings_manager.gd#L74
Though when I looked in **Project Settings**, a similar setting (`display/window/size/mode`) is available by default:
This PR redefines how `ESCSaveSettings.fullscreen` is initialized to be defined in terms of the existing setting (`true` if it is either "fullscreen" or "exclusive fullscreen") to avoid the crash.
It also adds a `register_setting()` call to `addons/escoria-core/plugin.gd` for …
> [bug] set ESCSaveSettings.fullscreen based on display/window/size/mode

- addons/escoria-ui-simplemouse/game.gd
To enable management of ESCAPE key action to pause
> [simple-mouse] Call super _input() game _input() method

- addons/escoria-dialog-simple/esc_dialog_simple.gd
- addons/escoria-dialog-simple/types/avatar.gd
- addons/escoria-dialog-simple/types/avatar.tscn
In Godot 4, popups do not behave the same way as in Godot 3, and so require the use of the base `Window` class but customized. It's also worth noting that `Window` is now derived from `Viewport` and not `Control`.
Also, the "has" method doesn't like working with invalid instances.
> fix: addresses Godot 4-specific issues related to popups and the "has" method

- addons/escoria-core/game/core-scripts/save_data/esc_save_manager.gd
fix(savegames): avoid crashing when loading savegame with items in inventory
> fix: avoid crashing when loading savegame with items in inventory
