device/ui/confirm_popup.tscn
=> Added missing confirm_popup.tscn file.

device/globals/game.gd, device/globals/global_vm.gd, device/globals/hud.gd, device/ui/confirm_popup.gd
Though this does not fix the issues in #46 it does update using the `pos` attribute to `position` and also uses the new style of setting the limits.
=> Update camera calls for Godot 3

device/globals/achievements.gd, device/globals/action_menu.gd, device/globals/dd_player.gd, device/globals/dialog_dialog.gd, device/globals/dialog_instance.gd, device/globals/dialog_player.gd, device/globals/game.gd, device/globals/global_vm.gd, device/globals/hud.gd, device/globals/item.gd, device/globals/main.gd, device/globals/save_data_icloud.gd, device/globals/scene_main.gd, device/globals/telon.gd, device/ui/main_menu.gd
I saw a complaint here that `Globals` is not defined. Despite my lack of experience here, I think `ProjectSettings` is what should be used here.
Thoughts?
=> Seems maybe Globals should be ProjectSettings here

device/globals/action_menu.gd, device/globals/dd_player.gd, device/globals/dialog_dialog.gd, device/globals/dialog_instance.gd, device/globals/dialog_player.gd, device/globals/game.gd, device/globals/global_vm.gd, device/globals/hud.gd, device/globals/item.gd, device/globals/main.gd, device/globals/scene_main.gd, device/globals/telon.gd, device/project.godot, device/ui/main_menu.gd
=> [RFC] ProjectSettings magic removal

device/globals/action_menu.gd, device/globals/game.gd, device/project.godot
This is work-in-progress for having the tooltip follow the mouse.
Currently hiding the tooltip when opening the action menu is broken. Currently I have no idea how to fix it, please help, unless I figure something out soon!
=> [RFC] Tooltip follows mouse

device/demo/ui/inventory.tscn, device/globals/inventory.gd
=> Get rid of unused and broken action code in inventory

device/globals/global_vm.gd, device/project.godot
=> Remove use_custom_camera

device/globals/bg_music.gd, device/globals/bg_music.tscn, doc/music.md
This should fix #35, but needs thorough testing.
=> Fix background music

device/globals/item.gd, device/globals/scene_base.gd, device/globals/scene_main.tscn
This adds to the item and base_scene gdscripts, a filter. There will not be other file types shown.
=> Made it easier to find esc files 3-17-18

doc/esc_reference.md
This adds code blocks to the documentation of esc_compile. Just a quick fix.
=> Esc_compile Documentation update

doc/esc_reference.md
This makes the commands and arguments stick out better.
=> Add more markdown ticks to esc reference

device/globals/interactive.gd, device/globals/item.gd
Tested with regular sprites and Spine
=> Make item.gd nodes react to lightmap

device/globals/item.gd, doc/setting_states.md
The endless spam on every finished animation had to be silenced.
I also explained in detail how to use `AnimationPlayer` to create states.
=> Polishing of set_state

tools/lockit.gd
Some slight modernisation of code, remove trailing commas in joined file lists and add comments to generated .csv files.
I've done some testing on produced .csv and .lockit files, but I'd like more eyes on it to make sure this doesn't cause any regressions.
=> Add comments to .csv generated by lockit.gd

device/globals/game.gd
I should have tested the previous commit for real, but it seemed so obvious.
This is what you get when the panic kicks in. Sorry.
=> Shuffle elif inventory to place so tooltips work

device/globals/player.gd
Fixes bug where last selected action would be repeated without opening action menu.
=> Fix repeated actions when using action menu

docs/export.md, docs/index.md
This was written in a hurry to help those entering Adventure Jam with an Escoria project, and there's room for improvement. See also #142.
=> Add very basic export instructions

device/globals/action_menu.gd, device/globals/dialog_instance.gd, device/globals/inventory.gd, device/ui/main_menu.gd
Most of this should be pretty obvious, except maybe the vertical align one.
But Godot is really bad at handling textual dimensions and margins and such, so enforcing
a newline is the only way to do it.
=> Some UI Fixes

device/globals/player.gd
=> Do not report errors if animations is actually set in player

device/globals/telon.gd, device/globals/telon.tscn, docs/telon.md
Use this for cutscenes which have any sort of timing
related to them, because user input like skipping dialog
would break it.
Disables saving as well, because loading a game from the
middle of a cutscene can't lead to anything good.
=> Implement disabling input through telon

device/globals/interactive.gd, device/globals/player.gd
Took a while to receive and integrate diagonal NPCs, but good things come to those who wait. Or maybe it's bugs. Or bug fixes. Anyway....
I noticed some time ago there's some strange skew with the player character's diagonal movements and wanted to see if it's true also for NPCs. It was. The demo scene doesn't really have what it takes to reproduce these problems, but I hope that doesn't prevent a merge.
This fixes what I could discern so far and replaces some less good checks with error-reporting.
=> Some angle fixes

device/project.godot, docs/export.md
If I'd have had time to properly test these during the past two weeks or so, this would have been a part of #205 :/
=> Use the "keep" stretch mode for HiDPI/Retina

device/globals/global_vm.gd, device/globals/item.gd, device/globals/trigger.gd
Noticed some missing signals were issuing errors for Sprite
and Node2D nodes. This just asks if the signals are supported.
=> Ask ClassDB about connecting signals

device/globals/esc_compile.gd, device/globals/global_vm.gd, docs/esc_reference.md
=> Implement check for item's activity

device/demo/fallbacks.esc, device/globals/dialog_dialog.gd, device/globals/esc_compile.gd, device/globals/global_vm.gd, device/globals/item.gd, device/globals/player.gd, device/globals/vm_level.gd, docs/esc_reference.md
As discussed with @StraToN on IRC, it's a bit annoying - especially for fallback events - that the player walks all across the room to say "meh".
This demonstrates how fallbacks, and custom events, can be made "telekinetic" with the `TK` flag.
It also contains a `FAST` flag for fast walking.
Once merged, it would be sweet to see what the community can come up with to make adventure games all the more awesome :)
=> Event flags

device/globals/game.gd, device/globals/global_vm.gd, device/globals/hud.gd, device/globals/item.gd, device/globals/trigger.gd, docs/esc_reference.md
There were some inexplicable issues with tooltips when trying to implement the `NO_TT` flag.
I had to make `run_event` use signals to get everything straight.
Please refer to the individual commit messages for more information.
=> Event work

device/globals/resource_queue.gd
This will hopefully help with the bug when exiting
a room while the resource_queue preloader is running.
Any touching the queue, even asking if it's ready, will
cause a deadlock or some other kind of stale mutex, so
events are (probably) required for anything to have a chance.
=> Add optional progress meters to resource_queue

device/globals/global_vm.gd, device/globals/item.gd, device/globals/main.gd, device/globals/scene_base.gd
Some code cleanups and such, and it seems to run faster.
=> Faster setup and some fixes

device/globals/item.gd, device/globals/player.gd, device/globals/scalenode.gd, device/globals/terrain.gd, device/globals/terrain_base.gd, device/globals/terrain_scalenodes.gd, docs/index.md, docs/terrain.md
Because the gradient approach is hard to deal with and slow in its implementation, have an alternative to use lerping instead.
=> Scalenode terrain

device/globals/item.gd, device/globals/tooltip.gd, device/globals/trigger.gd, docs/lang_tooltip_dialog.md
Accommodate tooltips for languages that have special needs in conjugation or capitalization.
=> Tooltip l10n hints

README.md
Reference the Escoria 2.0 branch.
=> Reference esc2-godot3.2 branch

device/globals/action_menu.gd, device/globals/global_vm.gd, device/globals/interactive.gd, device/globals/item.gd, device/globals/main.gd, device/globals/npc.gd, device/globals/tooltip.gd, device/globals/trigger.gd
Cloned repository does not work on stable Godot.
I made a few cosmetic changes to make it work.
=> Default scene doesn't work on Godot 3.2

device/globals/dialog_dialog.gd
(cherry pick from 74edead092f05afdf38339376d7f120fbadeb18d)
Branch esc2-godot3.2 can then be merged at flossmanualsfr/escoria as suggested at #267
=> Get Escoria 2 to work with Godot 3.2.3 stable

addons/escoria-core/game/core-scripts/esc_location.gd, addons/escoria-core/game/escoria.gd, game/rooms/room01/esc/room01.esc, game/rooms/room01/room01.tscn, game/rooms/room02/room02.tscn, game/rooms/room03/room03.tscn, game/rooms/room04/room04.tscn, game/rooms/room05/room05.tscn, game/rooms/room06/room06.tscn, game/rooms/room07/room07.tscn, game/rooms/room08/room08.tscn, game/rooms/room09/room09.tscn, game/rooms/room10/room10.tscn, game/ui/commons/options/options.gd, project.godot
This PR adds a new ESCLocation node that inherits Position2D. 
This allows ESC to use these locations to move ESCItem/ESCPlayer to these locations.
Fixes #306
=> Add ESCLocation node

addons/escoria-core/game/escoria.gd, addons/escoria-core/game/inputs_manager.gd, docs/esc.md
This fixes an issue with calculating the hover stack which resulted in #324.
=> Fixes an issue with calculating the hover stack which resulted in #324

addons/escoria-core/game/inputs_manager.gd, docs/esc.md
=> Renamed _hover_stack_pop() to _hover_stack_erase_item()

addons/escoria-core/game/core-scripts/esc_player.gd, docs/esc.md
=> Fix inputs on player CollisionShape2D node causing a crash

extractesc.py
This fixes the extraction command
=> fix: Fixed extraction command. Closes #338

addons/escoria-core/game/core-scripts/behaviors/esc_movable.gd, addons/escoria-core/game/core-scripts/esc/commands/teleport.gd, addons/escoria-core/game/core-scripts/esc/commands/teleport_pos.gd, addons/escoria-core/game/core-scripts/esc/esc_event_manager.gd, addons/escoria-core/game/core-scripts/esc/types/esc_dialog.gd, addons/escoria-core/game/core-scripts/esc_background.gd, addons/escoria-core/game/core-scripts/esc_player.gd, addons/escoria-core/game/core-scripts/save_data/esc_save_manager.gd, addons/escoria-core/game/core-scripts/save_data/esc_savesettings.gd, addons/escoria-core/game/escoria.gd, addons/escoria-core/game/main.gd, addons/escoria-core/game/scenes/dialogs/dialog_player.tscn, addons/escoria-core/game/scenes/transitions/transition.gd, docs/api/ESCBackground.md, docs/api/ESCDialog.md, docs/api/ESCMovable.md, docs/api/ESCPlayer.md, docs/api/ESCSaveSettings.md, docs/api/TeleportCommand.md, docs/api/TeleportPosCommand.md, docs/api/main.gd.md, docs/api/transition.gd.md, docs/esc.md, game/ui/commons/dialogs/dialog_box_inset.tscn, game/ui/commons/save/save_game.gd, project.godot
Fixed smaller issues, created new issues for the bigger ones.
Fixes #314
=> Checked all FIXMEs and TODOs

addons/escoria-core/game/core-scripts/resources/esc_animationname.gd, addons/escoria-core/game/core-scripts/resources/esc_animationresource.gd, addons/escoria-core/game/core-scripts/resources/esc_directionangle.gd, docs/api/AnimationName.md, docs/api/ESCDirectionAngle.md, project.godot
Fixes for the resource handling
=> Resource fixes

addons/escoria-core/game/core-scripts/esc/commands/spawn.gd, docs/api/ESCLogger.md, docs/api/SpawnCommand.md, docs/esc.md, game/characters/mark/mark.tscn, game/characters/mark/mark_animations.tres, project.godot
A few fixes in player animations and the spawn command.
=> Some fixes in mark_animations and span command

addons/escoria-core/game/core-scripts/esc_game.gd, addons/escoria-core/game/core-scripts/esc_location.gd, addons/escoria-core/game/core-scripts/esc_room.gd, addons/escoria-core/game/main.gd, addons/escoria-ui-9verbs/game.gd, addons/escoria-ui-simplemouse/game.gd, docs/api/ESCLocation.md, docs/api/main.gd.md, game/characters/worker/worker.tscn, game/rooms/room01/room01.tscn, game/rooms/room02/room02.tscn, game/rooms/room03/room03.tscn, game/rooms/room04/room04.tscn, game/rooms/room05/room05.tscn, game/rooms/room06/room06.tscn, game/rooms/room07/room07.tscn, game/rooms/room08/room08.tscn, game/rooms/room09/room09.tscn, game/rooms/room10/room10.tscn
Fixes #303 
Also:
Removed hardcoded node name "start_position" (to do so, added a "is_start_location" property to `ESCLocation`)
=> Removed hardcoded global_id "player"

addons/escoria-core/game/core-scripts/behaviors/esc_movable.gd, addons/escoria-core/game/core-scripts/esc/commands/anim.gd, addons/escoria-core/game/core-scripts/esc/commands/cut_scene.gd, addons/escoria-core/game/core-scripts/esc/types/esc_object.gd, addons/escoria-core/game/core-scripts/esc_animation_player.gd, addons/escoria-core/game/core-scripts/esc_item.gd, addons/escoria-core/testing/player_angles_finder.gd, docs/api/ESCAnimationPlayer.md, docs/api/ESCItem.md, game/characters/mark/mark.tscn, project.godot
=> Stable interface for both Animation player and Animated Sprite

addons/escoria-core/game/core-scripts/esc_background.gd, addons/escoria-core/game/inputs_manager.gd, addons/escoria-core/game/scenes/inventory/inventory_ui.gd, docs/api/ESCBackground.md, docs/api/ESCInputsManager.md
Moved signal connections to the right point and removed calls to private methods.
=> Optimized item and background signal handling 

addons/escoria-core/game/core-scripts/behaviors/esc_movable.gd, docs/api/ESCMovable.md
=> Refactor ESCMovable._is_angle_in_interval()

addons/escoria-core/game/inputs_manager.gd
Added required '%s' in strings.
=> Fixed error on double left click and right click in inventory.

addons/escoria-core/game/core-scripts/behaviors/esc_movable.gd, addons/escoria-core/game/core-scripts/esc/commands/set_animations.gd, addons/escoria-core/game/core-scripts/esc/commands/slide.gd, addons/escoria-core/game/core-scripts/esc/commands/slide_block.gd, addons/escoria-core/game/core-scripts/esc/commands/turn_to.gd, docs/api/ESCMovable.md, docs/api/SetAnimationsCommand.md, docs/api/SlideBlockCommand.md, docs/api/TurnToCommand.md, docs/esc.md, project.godot
This introduces the new "set_animations" command from my stream yesterday, fixes #386 and removes the @STUB keyword from already implemented ESC commands.
=> Small fixes and issue 386

addons/escoria-core/game/scenes/transitions/transition.gd, addons/escoria-core/game/scenes/transitions/transition.tscn, game/rooms/room01/room01.tscn
Fixes a bug where transitions animations in and out are inverted.
=> Fix inverted transitions in/out

addons/escoria-core/game/core-scripts/behaviors/esc_movable.gd, addons/escoria-core/game/core-scripts/esc/commands/turn_to.gd, addons/escoria-core/game/core-scripts/esc_controller.gd, addons/escoria-core/game/core-scripts/esc_item.gd, addons/escoria-core/game/scenes/inventory/inventory_ui.gd, docs/api/ESCItem.md, docs/api/ESCMovable.md, docs/api/TurnToCommand.md, docs/esc.md, game/items/escitems/r9_bottle.tscn, game/rooms/room01/esc/room01.esc, game/rooms/room01/item.tscn, game/rooms/room01/r_door.tscn, game/rooms/room01/room01.tscn
Fixes #385
+ Fixed a bug in esc_movable blocking player_orients_on_arrival for ESCLocation nodes
=> Re-implemented turn_to command

addons/escoria-core/game/core-scripts/behaviors/esc_movable.gd, addons/escoria-core/game/core-scripts/esc/commands/set_angle.gd, addons/escoria-core/game/core-scripts/esc/commands/turn_to.gd, addons/escoria-core/game/core-scripts/esc_item.gd, game/rooms/room01/esc/room01.esc, game/rooms/room10/esc/button_turn_to.esc
=> feat: Use wait parameter instead of immediate for turn_to and set_angle

addons/escoria-core/game/core-scripts/esc_controller.gd, game/rooms/room12/esc/room12.esc, game/rooms/room13/background.tscn, game/rooms/room13/esc/hint.esc, game/rooms/room13/esc/left_exit.esc, game/rooms/room13/esc/right_exit.esc, game/rooms/room13/esc/room13.esc, game/rooms/room13/r_door.tscn, game/rooms/room13/room13.tscn, game/rooms/room13/walkable_area.tscn
=> fix: Fixes for when the player scene isn't used in a room.

addons/escoria-core/game/core-scripts/esc/commands/inc_global.gd, addons/escoria-core/game/scenes/camera_player/esc_camera.gd, addons/escoria-ui-simplemouse/game.gd, project.godot
Room9: Global get with wrong method
Room13: caused by ESCCamera when no player scene set
Fixes godot-escoria/escoria-issues#37
=> Fix crashes in rooms 9 and 13

addons/escoria-core/game/core-scripts/esc/_test/test_esc_compiler.gd, addons/escoria-core/game/core-scripts/esc/types/esc_event.gd, addons/escoria-core/game/core-scripts/esc_controller.gd, game/rooms/room11/esc/mysterious_circle_nohud.esc
Fixes godot-escoria/escoria-issues#51
=> Rename flag NO_HUD to NO_UI (code)

addons/escoria-core/game/core-scripts/esc/esc_compiler.gd, addons/escoria-core/game/core-scripts/esc/types/esc_dialog.gd, addons/escoria-core/game/core-scripts/esc/types/esc_dialog_option.gd, addons/escoria-core/game/core-scripts/esc_item.gd, addons/escoria-dialog-simple/types/floating.gd, project.godot
… string and other dialog optimizations
=> Makes ESCDialog and ESCDialogOption instantiable without an ESC string

game/rooms/room15/room15.tscn
An ESC file was removed, but still referenced in an ESCObject, leading to an error on room loading.
=> Fix missing file error

addons/escoria-core/game/core-scripts/esc_room.gd, addons/escoria-core/game/main.gd, game/rooms/room15/room15.tscn
Fix regression introduced by commit d55c1394fd914b4b7fe7be44549a395214360022
=> Fix broken room camera

addons/escoria-core/game/core-scripts/esc_background.gd, addons/escoria-core/game/scenes/dialogs/esc_dialog_player.gd, project.godot
=> fix: Fixed input problems

addons/escoria-core/game/core-scripts/esc/esc_action_manager.gd, addons/escoria-core/game/core-scripts/esc_room.gd, addons/escoria-ui-9verbs/game.gd
Various fixes from chatting on Discord
=> Support fixes

addons/escoria-core/game/core-scripts/esc/commands/say.gd, addons/escoria-core/game/scenes/dialogs/esc_dialog_player.gd, addons/escoria-dialog-simple/types/floating.gd, game/rooms/room15/esc/say_long.esc, game/rooms/room15/room15.tscn, project.godot
Fixes positioning the text in the floating view type of the stock dialog manager Fixes godot-escoria/escoria-issues#59
Fixes detection of key and text Fixes godot-escoria/escoria-issues#58
=> fix: Say command fixes

addons/escoria-core/game/core-scripts/esc/commands/change_scene.gd, addons/escoria-core/game/core-scripts/esc/commands/queue_event.gd, addons/escoria-core/game/core-scripts/esc/esc_event_manager.gd, addons/escoria-core/game/core-scripts/esc/types/esc_command_argument_descriptor.gd, addons/escoria-core/game/core-scripts/esc_room.gd, addons/escoria-core/game/core-scripts/esc_tooltip.gd, addons/escoria-core/game/core-scripts/utils/esc_utils.gd, game/rooms/room06/room06.tscn, game/rooms/room14/esc/room14.esc, game/rooms/room14/esc/worker.esc, game/rooms/room14/room14.tscn, project.godot
Currently only available in the backend. We still ned an ESC implementation to run an event in the background.
Needed this for the ink bridge though.
godot-escoria/escoria-issues#53
=> feat: This introduces background events queue in Escoria

addons/escoria-core/game/core-scripts/esc_animation_player.gd
Fixes godot-escoria/escoria-issues#60
=> Check that ending animation is not looping before resetting it

addons/escoria-core/game/core-scripts/esc_animation_player.gd
fixes godot-escoria/escoria-issues#70
=> fix: Fixes signal handling on AnimationPlayer nodes.

addons/escoria-core/game/core-scripts/esc/commands/set_animations.gd, addons/escoria-core/game/core-scripts/esc/commands/stop_snd.gd, addons/escoria-core/game/core-scripts/esc/esc_globals_manager.gd, addons/escoria-core/game/core-scripts/esc_exit.gd, addons/escoria-core/game/core-scripts/esc_room.gd, addons/escoria-core/game/core-scripts/save_data/esc_save_manager.gd, game/characters/mark/mark.tscn, game/characters/mark/mark_animations_weird.tres, game/rooms/room14/room14.tscn, game/rooms/room15/esc/switch_animation.esc, game/rooms/room15/room15.tscn, saves/save_001.tres, saves/save_002.tres
Some further fixes
fixes #71
fixes #63
=> feat: Keep current animations resource

addons/escoria-core/game/core-scripts/esc/types/esc_object.gd, addons/escoria-core/game/core-scripts/esc_item.gd
closes godot-escoria/escoria-issues#79
=> feat: Fix set_interactive command

addons/escoria-core/game/core-scripts/esc_animation_player.gd, addons/escoria-core/game/core-scripts/log/esc_logger.gd, addons/escoria-core/game/main.gd
Fixes godot-escoria/escoria-issues#76
Fixes godot-escoria/escoria-issues#78
Fixes godot-escoria/escoria-issues#75
=> feat: Optimized animation handler and crashing

addons/escoria-core/game/scenes/inventory/inventory_ui.gd
fixes godot-escoria/escoria-issues#64
=> fix: Safety guards for disconnects

addons/escoria-core/game/core-scripts/esc_item.gd
Fixes https://github.com/godot-escoria/escoria-issues/issues/91
=> Fix input being blocked when item is not interactive #91

addons/escoria-core/game/core-scripts/esc/esc_globals_manager.gd
Fixes https://github.com/godot-escoria/escoria-issues/issues/87
=> Fix "global_changed" signal arguments order

addons/escoria-core/game/core-scripts/esc/esc_globals_manager.gd
Fixes a crash when setting globals for the first time.
=> Fix initial value of globals in signals emissions

addons/escoria-core/game/core-scripts/esc/esc_room_manager.gd, game/rooms/room16/esc/right_exit.esc, game/rooms/room16/esc/room16.esc, game/rooms/room17/esc/left_exit.esc, game/rooms/room17/room17.tscn, saves/save_003.tres
Fixes https://github.com/godot-escoria/escoria-issues/issues/95
=> Fix transitions not happening if the ESCRoom has no ESC script

addons/escoria-core/game/core-scripts/esc_game.gd, addons/escoria-ui-9verbs/game.gd, addons/escoria-ui-9verbs/game.tscn, addons/escoria-ui-simplemouse/game.gd, game/rooms/room17/background.tscn
Fixes https://github.com/godot-escoria/escoria-issues/issues/97
=> Set a default implementation for ESCGame._on_event_done()

addons/escoria-core/game/core-scripts/save_data/esc_save_manager.gd, addons/escoria-core/ui_library/menus/load_save/load/load_game.gd, addons/escoria-core/ui_library/menus/load_save/save/save_game.gd
Fixes https://github.com/godot-escoria/escoria-issues/issues/121
Fixes https://github.com/godot-escoria/escoria-issues/issues/122
=> Fix crash when save folder is empty and manage corrupted savegame file

addons/escoria-core/game/scenes/dialogs/esc_dialog_player.gd, addons/escoria-dialog-simple/esc_dialog_simple.gd
I haven't tested that yet, because develop is currently unstable. So I might check this again after #497 
But I don't see, why this shouldn't work as the code was bogus basically. 😄
=> feat: Removed obsolete code. Fixes godot-escoria/escoria-issues#99

addons/escoria-core/game/core-scripts/utils/esc_utils.gd
Fixes https://github.com/godot-escoria/escoria-issues/issues/141
@StraToN @dploeger @BHSDuncan
=> fix: stops negative numbers being interpreted as strings

addons/escoria-core/game/main.gd
Fixes https://github.com/godot-escoria/escoria-issues/issues/142
@dploeger @StraToN @BHSDuncan
=> fix: check to see if requested camera limit is invalid.

addons/escoria-core/game/scenes/camera_player/esc_camera.gd
Fixes https://github.com/godot-escoria/escoria-issues/issues/143
=> fix: fix camera_push tween error message - bug 143

addons/escoria-core/game/core-scripts/esc/commands/camera_push.gd, addons/escoria-core/game/core-scripts/esc/commands/camera_shift.gd
=> fix: validate checks on camera commands missing them.

game/rooms/room03/esc/button.esc, game/rooms/room03/esc/right_platform.esc, game/rooms/room03/esc/room03_bridge.esc, game/rooms/room03/room03.tscn
Fixed various logic issues where the button / bridge weren't in the correct status based on the rooms you'd visited and what you'd already done in room 3. Also added lots more comments.
=> fix: room3 logic issues

addons/escoria-core/game/core-scripts/esc_game.gd
Fixes https://github.com/godot-escoria/escoria-issues/issues/166 (signal attach/detach errors when you exit every room)
=> fix: Fix issue #166 - signal attach/detach errors when you exit every room

addons/escoria-core/game/escoria.gd
Found this during the stream and was annoyed. 😉
=> fix: Ensure escoria#apply_settings only called in game not editor

addons/escoria-core/game/core-scripts/esc/commands/walk_to_pos.gd, addons/escoria-core/game/core-scripts/esc/commands/walk_to_pos_block.gd
Fixes [144](https://github.com/godot-escoria/escoria-issues/issues/144)
=> feat: Add walk fast flag to walk_pos commands to make them consistent with the walk and walk_block commands

addons/escoria-core/game/core-scripts/behaviors/esc_movable.gd, addons/escoria-core/game/core-scripts/esc_item.gd
Fixes https://github.com/godot-escoria/escoria-issues/issues/155
cc @balloonpopper
=> Managed mirrored speak animations in ESCItem

addons/escoria-core/game/core-scripts/esc/commands/walk.gd, addons/escoria-core/game/core-scripts/esc/commands/walk_block.gd
Fixes [180](https://github.com/godot-escoria/escoria-issues/issues/180)
=> fix: Fix walk and walk_block to match the underlying code

addons/escoria-core/game/core-scripts/esc/commands/camera_push.gd
Fixes push to work as per :
https://docs.escoria-framework.org/en/devel/scripting/z_esc_reference.html#camera-push-target-time-type-api-doc
Fixes : https://github.com/godot-escoria/escoria-issues/issues/125
=> fix: Fix broken camera push.

addons/escoria-core/game/core-scripts/log/esc_logger.gd
Before : 2022-4-19T1372
After:    2022-04-19T13:**0**7:**0**2
=> fix: fixes incorrect date formatting

addons/escoria-core/game/core-scripts/esc/esc_object_manager.gd, addons/escoria-core/game/core-scripts/esc/types/esc_object.gd, addons/escoria-core/game/scenes/sound/esc_music_player.gd, addons/escoria-core/game/scenes/sound/esc_speech_player.gd
Fixes https://github.com/godot-escoria/escoria-issues/issues/193
Unblocks https://github.com/godot-escoria/escoria-demo-game/pull/532
=> feat: Save objects states in Obj Manager to keep them btwn rooms

addons/escoria-core/game/core-scripts/esc/commands/say.gd
Fixes https://github.com/godot-escoria/escoria-issues/issues/120
(Note that the links won't be valid until https://github.com/godot-escoria/escoria-docs/pull/51 is committed)
=> docs: Updated say command docs for audio and translations

addons/escoria-core/game/core-scripts/esc_game.gd, addons/escoria-core/game/core-scripts/log/esc_logger.gd, addons/escoria-core/game/escoria.gd
Supersedes #579 
I did nothing special apart from fixing conflicts. 
All credits go to @jeancallisti 
Thanks!
=> Prefixed all Escoria console output with 'ESC'

addons/escoria-core/game/core-scripts/esc/esc_event_manager.gd
Fixes https://github.com/godot-escoria/escoria-issues/issues/245
=> fix: prevents the same event from being queued multiple times in a row

addons/escoria-core/game/core-scripts/esc/commands/custom.gd, addons/escoria-core/game/core-scripts/esc/types/esc_command.gd, addons/escoria-core/game/core-scripts/esc/types/esc_command_argument_descriptor.gd, addons/escoria-core/game/main.gd, game/rooms/room03/esc/room03_bridge.esc
Fixes https://github.com/godot-escoria/escoria-issues/issues/106
=> fix: implement varargs for ESC commands. 'custom' makes use of this #592

addons/escoria-core/game/core-scripts/esc/commands/play_snd.gd, addons/escoria-core/game/core-scripts/esc/commands/wait.gd, addons/escoria-core/game/core-scripts/esc/commands/walk.gd, addons/escoria-core/game/core-scripts/esc/commands/walk_block.gd, addons/escoria-core/game/core-scripts/esc/commands/walk_to_pos.gd, addons/escoria-core/game/core-scripts/esc/commands/walk_to_pos_block.gd, addons/escoria-core/game/core-scripts/esc/esc_action_manager.gd, addons/escoria-core/game/core-scripts/esc/esc_event_manager.gd, addons/escoria-core/game/core-scripts/esc/esc_object_manager.gd, addons/escoria-core/game/core-scripts/esc/esc_room_manager.gd, addons/escoria-core/game/core-scripts/esc/types/esc_base_command.gd, addons/escoria-core/game/core-scripts/esc/types/esc_execution.gd, addons/escoria-core/game/core-scripts/esc_game.gd, addons/escoria-core/game/core-scripts/save_data/esc_save_manager.gd, addons/escoria-core/game/escoria.gd, addons/escoria-core/game/inputs_manager.gd, addons/escoria-core/ui_library/tools/room_select/room_select.gd, addons/escoria-ui-9verbs/game.gd, game/rooms/intro/esc/intro.esc, game/rooms/room07/room07.tscn
Fixes https://github.com/godot-escoria/escoria-issues/issues/249
Fixes https://github.com/godot-escoria/escoria-issues/issues/257
Fixes https://github.com/godot-escoria/escoria-issues/issues/161
Fixes https://github.com/godot-escoria/escoria-issues/issues/263
=> fix: prevents improper events/commands from being queued while changing scenes

addons/escoria-core/game/core-scripts/esc/commands/custom.gd, addons/escoria-core/game/core-scripts/esc/commands/print.gd, addons/escoria-core/game/core-scripts/esc/commands/say.gd, addons/escoria-core/game/core-scripts/esc/esc_compiler.gd, addons/escoria-core/game/core-scripts/log/esc_logger.gd, game/rooms/room03/esc/room03_bridge.esc
It annoyed me that after the change to allow parameters to be passed to "custom" that I couldn't pass Escoria variables.
Fixes : https://github.com/godot-escoria/escoria-issues/issues/261
=> feature: Added ability to use Escoria variables with the custom command

addons/escoria-core/game/core-scripts/esc/esc_object_manager.gd
=> Fix a typo in a log call

addons/escoria-core/game/core-scripts/esc/esc_room_manager.gd
Fixes https://github.com/godot-escoria/escoria-issues/issues/289
=> fix: prevents changing scenes to the same scene as is current

addons/escoria-core/game/core-scripts/esc/esc_event_manager.gd
Closes https://github.com/godot-escoria/escoria-issues/issues/275
=> fix: disallows input during any transition call

addons/escoria-ui-9verbs/tooltip/tooltip_action_target.gd, addons/escoria-ui-keyboard-9verbs/tooltip/tooltip_action_target.gd
Added ACTION_PREPS dictionary to settings/escoria/ui
Modified `esc_tooltip.gd` to make use of this dictionary.
Fixes https://github.com/godot-escoria/escoria-issues/issues/176
=> fix: "Give xyz with" should say "give xyz to" (#176)

addons/escoria-core/game/core-scripts/esc_game.gd
Fixes https://github.com/godot-escoria/escoria-issues/issues/110
=> fix: guards against scenes with no player set or loaded

addons/escoria-core/game/core-scripts/esc/esc_action_manager.gd, addons/escoria-core/game/core-scripts/esc_game.gd, addons/escoria-core/game/core-scripts/save_data/esc_savesettings.gd, addons/escoria-core/game/core-scripts/save_data/esc_settings_manager.gd, addons/escoria-core/game/esc_autoload.gd, addons/escoria-core/game/esc_project_settings_manager.gd, addons/escoria-core/game/escoria.gd, addons/escoria-core/game/scenes/sound/esc_music_player.gd, addons/escoria-core/game/scenes/sound/esc_music_player.tscn, addons/escoria-core/game/scenes/sound/esc_sound_player.gd, addons/escoria-core/game/scenes/sound/esc_sound_player.tscn, addons/escoria-core/game/scenes/sound/esc_speech_player.gd, addons/escoria-core/game/scenes/sound/esc_speech_player.tscn, addons/escoria-core/ui_library/menus/options/options.gd, addons/escoria-core/ui_library/menus/options/options.tscn, addons/escoria-ui-9verbs/game.gd, addons/escoria-ui-keyboard-9verbs/game.gd, addons/escoria-ui-simplemouse/game.gd, project.godot
- fixed: speech was not paused during pause menu
- fixed: allow sound levels to reach min value 0.0 (=muted)
=> Unified settings management and sound fixes

addons/escoria-core/game/core-scripts/esc/esc_action_manager.gd
Fixes https://github.com/godot-escoria/escoria-issues/issues/296
=> Fix: get_simple_path not working properly in Godot 3.5

addons/escoria-ui-9verbs/game.gd
Fixes https://github.com/godot-escoria/escoria-issues/issues/293
=> fix: clears tooltip after any action has finished regardless of success

addons/escoria-core/game/core-scripts/esc/commands/queue_event.gd, addons/escoria-core/game/core-scripts/esc/commands/repeat.gd, addons/escoria-core/game/core-scripts/esc/commands/set_angle.gd, addons/escoria-core/game/core-scripts/esc/commands/set_state.gd, addons/escoria-core/game/core-scripts/esc/commands/show_menu.gd, addons/escoria-core/game/core-scripts/esc/commands/stop.gd, addons/escoria-core/game/core-scripts/esc/commands/stop_snd.gd, addons/escoria-core/game/core-scripts/esc/commands/transition.gd, addons/escoria-core/game/core-scripts/esc/commands/turn_to.gd, addons/escoria-core/game/core-scripts/esc/commands/walk.gd, addons/escoria-core/game/core-scripts/esc/commands/walk_block.gd, game/rooms/room16/esc/current_scene_button.esc, game/rooms/room16/esc/room16.esc, game/rooms/room16/esc/worker_script.esc, game/rooms/room16/room16.tscn
Updates some documentation along with room changes to demonstrate usage of commands without examples
Fixes https://github.com/godot-escoria/escoria-issues/issues/181
=> fix: Issue 181

addons/escoria-core/game/core-scripts/esc/commands/camera_push.gd, addons/escoria-core/game/core-scripts/esc/commands/camera_set_limits.gd, addons/escoria-core/game/core-scripts/esc/commands/camera_set_pos.gd, addons/escoria-core/game/core-scripts/esc/commands/camera_set_target.gd, addons/escoria-core/game/core-scripts/esc/commands/camera_set_zoom.gd, addons/escoria-core/game/core-scripts/esc/commands/camera_shift.gd, addons/escoria-core/game/core-scripts/esc/types/esc_camera_base_command.gd, addons/escoria-core/game/scenes/camera_player/esc_camera.gd, game/rooms/room07/room07.tscn
Fixes https://github.com/godot-escoria/escoria-issues/issues/137
=> fix: addresses camera lag and other issues related to DRAG_CENTER anchor mode and drag margins

addons/escoria-core/game/core-scripts/esc/commands/camera_push_block.gd, addons/escoria-core/game/core-scripts/esc/commands/camera_set_pos_block.gd, addons/escoria-core/game/core-scripts/esc/commands/camera_set_target_block.gd, addons/escoria-core/game/core-scripts/esc/commands/camera_set_zoom_block.gd, addons/escoria-core/game/core-scripts/esc/commands/camera_set_zoom_height_block.gd, addons/escoria-core/game/core-scripts/esc/commands/camera_shift_block.gd, addons/escoria-core/game/scenes/camera_player/esc_camera.gd, game/rooms/room07/esc/button_push.esc, game/rooms/room07/esc/button_set_pos.esc, game/rooms/room07/esc/button_zoom.esc, game/rooms/room07/esc/lift_door_floor_1.esc, game/rooms/room07/esc/lift_door_floor_2.esc, game/rooms/room07/esc/lower_stairs.esc, game/rooms/room07/esc/room07.esc, game/rooms/room07/esc/upper_stairs.esc, game/rooms/room07/room07.tscn
Closes https://github.com/godot-escoria/escoria-issues/issues/138
=> feat: adds blocking versions of camera commands that can tween/transition

addons/escoria-core/game/esc_project_settings_manager.gd, addons/escoria-dialog-simple/plugin.gd, addons/escoria-dialog-simple/types/avatar.gd, addons/escoria-dialog-simple/types/floating.gd, project.godot
Closes https://github.com/godot-escoria/escoria-issues/issues/82
=> feat: adds adjustable reading speed/display time

addons/escoria-core/game/esc_inputs_manager.gd, game/rooms/room18/room18.tscn
Fixes https://github.com/godot-escoria/escoria-issues/issues/111
Tested in room 18 and the issues are fixed.
=> fix: Issue 111 - overlapping non-interactive items

addons/escoria-wizard/CharacterCreator.gd, addons/escoria-wizard/CharacterCreator.tscn
This lets the wizard create 1 or 2 direction characters as well as the existing 4/8. Helpful when creating an NPC that you'll talk to but otherwise doesn't do anything.
=> feat: Added 1 and 2 direction animations to wizard character creator

.github/CODEOWNERS
I've removed myself for the time being as I can't contribute currently and are bombed with mails. :)
=> chore: Remove dploeger for the time being

addons/escoria-core/game/core-scripts/esc/esc_action_manager.gd, addons/escoria-ui-9verbs/game.gd, project.godot
Fixes https://github.com/godot-escoria/escoria-issues/issues/342
=> fix: clears tooltip when event is finished and adds in missing check for item combination when in inventory

addons/escoria-core/game/esc_inputs_manager.gd
Fixes https://github.com/godot-escoria/escoria-issues/issues/312
=> fix: necessary in order to prevent error message from printing out

addons/escoria-core/game/core-scripts/esc_item.gd
Movable commands on non-movable items will be handled gracefully.
Non-movable ESCItems will default to direction[0] for talk animations if they exist.
=> fix: Movable commands on non-movable items will be handled gracefully.

addons/escoria-core/game/core-scripts/esc_item.gd, game/rooms/room05/room05.tscn
Fixes: https://github.com/godot-escoria/escoria-issues/issues/348
Also moved a few things around to put them on even coordinates for neatness.
=> fix: Debug message for when an item has no ESCLocation

addons/escoria-core/game/escoria.gd
Fixes https://github.com/godot-escoria/escoria-issues/issues/351
=> fix: Fix bug where inventory is invisible by default

addons/escoria-core/game/core-scripts/esc/types/esc_dialog.gd
Fixes https://github.com/godot-escoria/escoria-issues/issues/344
=> fix: forces current_state updates as options don't always yield

addons/escoria-dialog-simple/esc_dialog_simple.gd
Fixes error: Attempted method call on a deleted object. Attempt to call function 'voice_audio_finished' in base 'previously freed instance' on null instance.
Discord: https://discord.com/channels/884336424780984330/1073799180960682064/1073799180960682064
=> fix: Attempted method call on a deleted object.

addons/escoria-core/game/core-scripts/esc/esc_object_manager.gd
Fixes https://github.com/godot-escoria/escoria-issues/issues/333
=> fix: Issue-333 Error when room has no Global ID set

addons/escoria-core/game/esc_logger.gd
Needed for PR [#713](https://github.com/godot-escoria/escoria-demo-game/pull/713)
=> Create new static logger functions (to be used only in static classes)

addons/escoria-core/game/core-scripts/behaviors/esc_movable.gd
Author: Fritz (fritzmenzer@Discord)
=> Fix: walking speed depending on Z value

addons/escoria-ui-simplemouse/game.tscn
So that they react to input as intended.
=> [Simple-mouse] Make Menu and Room-select buttons go OVER inventory out area
